### PR TITLE
Upper bound model and accompanying notebook added.

### PR DESCRIPTION
**Pull request by markvdw**
I added a model implementing Titsias' upper bound, as referenced in #463 (plus accompanying test). I also added a notebook showing some results of messing around with the bound. These will also be part of my thesis, but I think they'd be useful here as well.

The code essentially implements the upper bound, and also allows for minimising the upper bound. For fixed hyperparameters, this is a good way to find the tightest upper bound. It doesn't make sense to minimise this upper bound with free hyperparameters as there are always poor hyperparameter settings where the upper bound is tight. Currently, it's up to the user to use this correctly. This should all be extensively shown in the notebook.

The notebook also discusses using the upper bound to prove when FITC is over-estimating the marginal likelihood, without needing to calculate the marginal likelihood.

### CODE REVIEW

**Comment by markvdw** [comment]
This is strange, codeship seems to fail on a notebook I didn't touch, and on a `KeyboardInterrupt`?

**Comment by markvdw** [comment]
Strange, a simple re-run of the test made it work. Perhaps this is non-determinancy? Probably good to keep an eye out for this in the future, but I don't think it's relevant to the current PR. As far as I'm concerned this is ready to go.

**Comment by alexggmatthews** [comment]
Hmm that is annoying. Seems to be happening relatively often at the moment. @javdrher has a similar problem on #456 . Possibly to do with a timeout?

**Comment by jameshensman** [comment]
The notebooks take a long time to test. My guess is that they sometimes time out if codeship is under a heavy load.

**Comment by awav** [comment]
@markvdw I had same issue in #471 with unstable notebook tests. The problem is that notebook error output doesn't tell what exactly happen at a computation cell. I added in-depth error message as the aftermath, but tests had started passing after that :)

**Comment by markvdw** [comment]
A simple re-run of the notebooks worked fine here. I think it was a timeout issue.

Anyway, as far as I'm concerned, this is ready to be merged.

**Pull request closed without merging**
