### PR TITLE
Pip installation for GPflow

### PR DESCRIPTION
**Pull request by alexisboukouvalas**
Addresses #51 
Following this [guide](http://peterdowns.com/posts/first-time-with-pypi.html) I have created a test pip package for GPflow - see [here](https://testpypi.python.org/pypi/GPflow).

If you are happy to proceed, we just need to do:
python setup.py register -r pypi
python setup.py sdist upload -r pypi
to publish the package.

You can test pip installation by pointing pip to test server:
pip install -i https://testpypi.python.org/pypi GPflow

*Should installation fail if tensorflow is not installed?* Currently it does not but fails when importing GPflow.

### CODE REVIEW

**Comment by jameshensman** [comment]
Looks good. 

Perhaps we could all have a go at installing the pip package from the testing pypi as Alexis details above, and report back here? 

You can use virtual environments (or conda envs) to avoid messing up core setups.

**Comment by alexisboukouvalas** [comment]
Great suggestion @jameshensman I tested pip installation on python 2.7 using conda environment. This may be useful for other people as well
```
conda create --yes -n condaenv python=2.7
conda install --yes -n condaenv pip
conda install --yes -n condaenv scipy
conda install --yes -n condaenv nose
source activate condaenv
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
pip install pandas
pip install -i https://testpypi.python.org/pypi GPflow
```

Also I incremented the version as I could not update the PyPI uploaded version. Apparently you cannot edit an uploaded version on PyPI even on the [test server](https://github.com/pypa/packaging-problems/issues/74).
I can remove the versioning change if needed or keep it in if you think it's a good idea.

**Comment by rhofour** [comment]
Is something holding this up? I have a little time and I'd be willing to help out.

**Comment by alexisboukouvalas** [comment]
hi @rhofour we would greatly appreciate your help.
Could you 
1. Code review the code for robustness and readability.
2. Test the installation. I have tried this on a variety of systems (ubuntu, mac os) but would really appreciate some more coverage.

**Comment by alexggmatthews** [comment]
@alexisboukouvalas hope this finds you well. What's the status of this one?  We don't have any user ops these days so that may well help.

**Comment by alexisboukouvalas** [comment]
I would like to update the pull request as pypi now understands markdown
which should simplify the code.
Thanks Alex for removing user ops, this should help with all the
installation issues I have seen.

**Comment by alexisboukouvalas** [comment]
I suggest to close this pull request and implement a new approach.
Pypi now supports markdown so no need to convert our README.md .
Once #452 is fixed and we have the pep8 compliant name gpflow, I suggest we use Travis to deploy the package. Specifically Travis supports deployment whenever the [version is changed](https://docs.travis-ci.com/user/deployment/pypi/).
This would allow for a completely automatic process.
@jameshensman @alexggmatthews @awav thoughts?

I am also happy if someone else would like to implement this pull request.

**Comment by st--** [comment]
@alexisboukouvalas what's the status on this? do you know how we can get travis to deploy the pip package?

**Comment by alexisboukouvalas** [comment]
hi @st-- the instructions on getting travis to deploy the pip package are here : 
https://docs.travis-ci.com/user/deployment/pypi/ 
I have never used it in practice but it looks straightforward.

**Pull request closed without merging**
