### PR TITLE
Remove TF import in setup.py

### PR DESCRIPTION
**Pull request by javdrher**
Following #487 , removal of the TF import in setup.py. This allows single-command installation in clean environments, without first installing TF. I also updated the installation instructions in the documentation and readme.

### CODE REVIEW

**Comment by markvdw** [comment]
Hi @javdrher, thanks for the comprehensive patch! The only thing I want to check before merging is that there's no problem with tensorflow being in install_requires, while tensorflow-gpu being in extras. This won't somehow break if someone only has tensorflow-gpu installed?

(Just checking to be sure, my knowledge of the Python installation system is not deep.)

**Comment by javdrher** [comment]
Just installed tensorflow-gpu in an empty environment:
```
$ pip install tensorflow-gpu
Collecting tensorflow-gpu
  Using cached tensorflow_gpu-1.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy>=1.11.0 (from tensorflow-gpu)
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: wheel>=0.26 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow-gpu)
Collecting tensorflow-tensorboard<0.2.0,>=0.1.0 (from tensorflow-gpu)
  Using cached tensorflow_tensorboard-0.1.4-py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow-gpu)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow-gpu)
  Using cached protobuf-3.4.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
Collecting tensorflow>=1.2.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
  Using cached tensorflow-1.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow-gpu)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from protobuf>=3.3.0->tensorflow-gpu)
Installing collected packages: numpy, werkzeug, six, html5lib, protobuf, tensorflow, markdown, bleach, tensorflow-tensorboard, tensorflow-gpu
Successfully installed bleach-1.5.0 html5lib-0.9999999 markdown-2.6.8 numpy-1.13.1 protobuf-3.4.0 six-1.10.0 tensorflow-1.3.0 tensorflow-gpu-1.3.0 tensorflow-tensorboard-0.1.4 werkzeug-0.12.2
```
That seems to install tensorflow as well. Then installing GPflow skips tensorflow
```
$ pip install .
Processing /home/javdrher/GPflow
Requirement already satisfied: numpy>=1.9 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from GPflow==0.3.8)
Collecting scipy>=0.16 (from GPflow==0.3.8)
  Using cached scipy-0.19.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: tensorflow>=1.0.0 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from GPflow==0.3.8)
Requirement already satisfied: wheel>=0.26 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: protobuf>=3.3.0 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: tensorflow-tensorboard<0.2.0,>=0.1.0 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: six>=1.10.0 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: setuptools in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from protobuf>=3.3.0->tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: markdown>=2.6.8 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: html5lib==0.9999999 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: bleach==1.5.0 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->GPflow==0.3.8)
Requirement already satisfied: werkzeug>=0.11.10 in /home/javdrher/.virtualenvs/installtest/lib/python3.5/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow>=1.0.0->GPflow==0.3.8)
Installing collected packages: scipy, GPflow
  Running setup.py install for GPflow ... done
Successfully installed GPflow-0.3.8 scipy-0.19.1
```
So I think this should be ok. Other scenario I checked: what if tensorflow-gpu < 1.0 is installed. Turns out the installation then upgrades tensorflow and disabled the GPU support until that package is (manually upgraded as well). 

If you don't feel confident about this, we could also put an import tensorflow inside a catch block in setup.py. If it raises an error, tensorflow is added as dependency to install requires. If the import succeeds it isn't so the existing installation isn't touched in anyway (although this could imply very old and incompatible tensorflow installations are not upgraded during installation).

**Comment by markvdw** [comment]
Ok thanks for checking. So the only issue is with someone who has an old version of `tensorflow-gpu` (< tf1.0), in which case this will be upgraded to a new version of tensorflow, but non-gpu.

I would say that this is acceptable. Getting the GPU up and running can't really be done using pip by itself anyway (as it requires the installation of CUDA, CUDNN etc), so I don't think someone who uses the GPU should expect it to be transparent when installing GPflow either. I've added a note to the readme.

@alexggmatthews @jameshensman, I'll merge this now in the interest of moving things along, but I'm happy to fix this if you think it's the wrong judgement.

**Comment by javdrher** [comment]
@markvdw I just checked, it seems that older tensorflow-gpu packages (e.g. 1.1)  do not install the accompanying tensorflow package. This means a newer a newer tensorflow (cpu is installed).

**Comment by markvdw** [comment]
@javdrher are you still ok to add the import check that you suggested? I think that's a good solution until tf1.3 becomes widespread.

**Comment by markvdw** [comment]
Great thanks!

**Pull request merged**
