### PR TITLE
Recompilation of nested models

### PR DESCRIPTION
**Pull request by javdrher**
As reported earlier (#442) the current code assumes the highest_parent is a model, which can be recompiled. If this is isn't the case (in gpflowopt it usually isn't) a recompile flag is set on objects that can not recompile. Because of this, everything which should result in a recompile in gpflowopt is broken (and for instance VGP can not be used as a model as it requires recompilation after data updates).

This code should solve this. I added a rather generic method to parentable to perform some queries on the parent nodes. The behavior is as follows:

-  when a recompile is required, the highest_parent which has a _needs_recompile flag is found and set to recompile. 
- kill_autoflow still starts at the highest_parent as the graph of autoflow methods might contain parts of children which were recompiled. 

I also looked at the reassignment of Params and tried to cover all cases I could think of and added some tests.

### CODE REVIEW

**Comment by javdrher** [comment]
Does anyone know why the codeship build failed? I do not seem to have the permissions to view the log and locally, I have no faillures on python 2.7.

**Comment by alexggmatthews** [comment]
There must be a way of doing this long term but @javdrher here to keep things moving here is the test output from codeship.

```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
......................../home/rof/miniconda/envs/condaenv/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
"Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
.............../home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.ekernels.Add'>. Use GPflow.ekernels instead.
str(type(self)))
/home/rof/src/github.com/GPflow/GPflow/GPflow/ekernels.py:251: UserWarning: GPflow.ekernels.Add: Using numerical quadrature for kernel expectation cross terms.
warnings.warn("GPflow.ekernels.Add: Using numerical quadrature for kernel expectation cross terms.")
./home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.kernels.RBF'>. Use GPflow.ekernels instead.
str(type(self)))
/home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.kernels.Linear'>. Use GPflow.ekernels instead.
str(type(self)))
....../home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.kernels.Add'>. Use GPflow.ekernels instead.
str(type(self)))
......../home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.kernels.Prod'>. Use GPflow.ekernels instead.
str(type(self)))
...../home/rof/src/github.com/GPflow/GPflow/GPflow/kernels.py:150: UserWarning: Using numerical quadrature for kernel expectation of <class 'GPflow.kernels.PeriodicKernel'>. Use GPflow.ekernels instead.
str(type(self)))
..............................................................................................................W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
F................................................RUNNING THE L-BFGS-B CODE

* * *

Machine precision = 2.220D-16
N =            1     M =           10
This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.45868D+00    |proj g|=  2.64240D-01

At iterate    1    f=  2.43844D+00    |proj g|=  2.25400D-01

At iterate    2    f=  2.38630D+00    |proj g|=  8.30794D-04

At iterate    3    f=  2.38630D+00    |proj g|=  1.44612D-05

At iterate    4    f=  2.38630D+00    |proj g|=  3.26916D-12

* * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

* * *

N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
1      4      5      1     0     0   3.269D-12   2.386D+00
F =   2.3862953611198905     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            

Cauchy                time 0.000E+00 seconds.
Subspace minimization time 0.000E+00 seconds.
Line search           time 0.000E+00 seconds.

Total User time 0.000E+00 seconds.

...................................................../home/rof/src/github.com/GPflow/GPflow/GPflow/session.py:15: UserWarning: Outputting a trace for each run. May result in large disk usage.
warnings.warn("Outputting a trace for each run. May result in large disk usage.")
....................
======================================================================
FAIL: Test all notebooks except blacklist. Blacklisted notebooks take too long.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/GPflow/GPflow/testing/test_notebooks.py", line 40, in test_all_notebooks
self._execNotebook(ep, notebook_filename, nbpath)
File "/home/rof/src/github.com/GPflow/GPflow/testing/test_notebooks.py", line 26, in _execNotebook
See above for error.' % notebook_filename)
AssertionError: Error executing the notebook /home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/multiclass.ipynb.                                        See above for error.
-------------------- >> begin captured stdout << ---------------------
/home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/vgp_notes.ipynb took 3.25192 seconds.
/home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/structure.ipynb took 4.97398 seconds.
/home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/settings.ipynb took 15.9977 seconds.
/home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/regression_with_updated_data.ipynb took 118.712 seconds.
/home/rof/src/github.com/GPflow/GPflow/testing/../doc/source/notebooks/ordinal.ipynb took 79.3793 seconds.
------------------------------------------------------------
Traceback (most recent call last):
File "/home/rof/src/github.com/GPflow/GPflow/testing/test_notebooks.py", line 20, in _execNotebook
ep.preprocess(nb, {'metadata': {'path': nbpath}})
File "/home/rof/miniconda/envs/condaenv/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 242, in preprocess
nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
File "/home/rof/miniconda/envs/condaenv/lib/python2.7/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
File "/home/rof/miniconda/envs/condaenv/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 275, in preprocess_cell
raise CellExecutionError(msg)
CellExecutionError: An error occurred while executing the following cell:
------------------
samples = m.sample(500, verbose=True, epsilon=0.04, Lmax=15)
------------------

KeyboardInterrupt: 

------------------------------------------------------------

--------------------- >> end captured stdout << ----------------------

Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
GPflow.py                         4      0   100%   
GPflow/_settings.py              84      0   100%   
GPflow/_version.py                1      0   100%   
GPflow/conditionals.py           46      0   100%   
GPflow/densities.py              36      0   100%   
GPflow/ekernels.py              171      0   100%   
GPflow/gplvm.py                 112      0   100%   
GPflow/gpmc.py                   32      0   100%   
GPflow/gpr.py                    35      0   100%   
GPflow/hmc.py                    44      0   100%   
GPflow/kernels.py               349      0   100%   
GPflow/kullback_leiblers.py      42      0   100%   
GPflow/likelihoods.py           268      0   100%   
GPflow/mean_functions.py         61      0   100%   
GPflow/minibatch.py              44      0   100%   
GPflow/model.py                 144      1    99%   50
GPflow/param.py                 366      2    99%   72, 487
GPflow/priors.py                 55      0   100%   
GPflow/quadrature.py             26      0   100%   
GPflow/scoping.py                10      0   100%   
GPflow/session.py                46      0   100%   
GPflow/sgpmc.py                  24      0   100%   
GPflow/sgpr.py                  111      0   100%   
GPflow/svgp.py                   46      0   100%   
GPflow/tf_hacks.py                4      0   100%   
GPflow/tf_wraps.py                9      0   100%   
GPflow/transforms.py            132      0   100%   
GPflow/vgp.py                    84      1    99%   235
-----------------------------------------------------------
TOTAL                          2386      4    99%   
----------------------------------------------------------------------
Ran 291 tests in 870.150s

FAILED (failures=1)
```

**Comment by alexggmatthews** [comment]
@jameshensman could we give @javdrher the relevant codeship permissions so he can see the build please? Thanks.

**Comment by javdrher** [comment]
Hmm seems to have been killed by codeship, possibly because it was running too long?

**Comment by st--** [comment]
@javdrher any objections to closing this? (Is this still an issue with new gpflow?)

**Pull request closed without merging**
