### PR TITLE
Tf wraps

### LINKED ISSUE #187: tf_hacks -> tf_wraps
I don't think the name for tf_hacks.py accurately represents its content. In particular I think the use of the term "hack" is a bit strong for the work arounds in there. I suggest changing the name to something more neutral like tf_wraps.

### PR DESCRIPTION
**Pull request by alexggmatthews**
Fixes #187

### CODE REVIEW

**Comment by jameshensman** [comment]
api change: requires version bump imo.

**Comment by alexggmatthews** [comment]
Do we think it is big enough for a version bump on its own?

**Comment by alexggmatthews** [comment]
@jameshensman perhaps we could wait to merge this one until we've got some of the other pending PRs in so we don't have too much version number creep. What do you think?

**Comment by jameshensman** [comment]
@alexggmatthews with the scopes and config file, I think there's enough to make a new minor version.

I'm happy with your changes on this PR. If you're happy with mine, I suggest we merge.

**Comment by alexggmatthews** [comment]
Yes I'm happy with your changes to this.

**Pull request merged**
