### PR TITLE
Lower-bound default positive transform

### PR DESCRIPTION
**Pull request by st--**
Change `gpflow.base.positive()` to behave like GPflow-1's `gpflow.transforms.positive`, i.e. instead of a "pure" softplus (log(1+exp(x)), lower-bound it by adding a small value (default = 1e-6), which prevents positively-constrained hyperparameters such as lengthscales from going too small.

This PR gives gpflow2 the same default behaviour as gpflow1. Relates to issues such as #1095. Probably warrants some discussion before merging.

### CODE REVIEW

**Comment by awav** [comment]
Hello @st--, I apologize for closing your PR. It was closed automatically when I moved `develop-2.0` to the `develop`. Could you re-open the PR? Thanks!

**Comment by frgsimpson** [comment]
I'd be keen to make any default lower bound much smaller then 1e-6, as the hyperparameters of spectral mixture kernels routinely fall to around 1e-10.

One possibility would be to enforce parameters to have well defined priors, and a default lower bound can naturally be accommodated there. (I'm a bit hesitant to put it inside a transform where the user may not be expecting it.)

**Comment by jahall** [comment]
I noticed when making changes for #1148 that there is a bug in current `positive` function. Specifically that the `lower` override arg is not getting applied. This _might_ be the root cause of errors...though not investigated further yet.

Current code:
```
def positive(lower: Optional[float] = None):
    lower_value = config.default_positive_minimum()
    if lower_value is None:
        return tfp.bijectors.Softplus()
    ...
```
Corrected:
```
def positive(lower: Optional[float] = None):
    if lower is None:
        lower = config.default_positive_minimum()
    if lower is None:
        return tfp.bijectors.Softplus()
    ...
```

**Comment by jahall** [comment]
Actually, ignore me...the root of your problem is that when you compose the `tfp.bijectors.Chain` you need to perform the shift _after_ the positive bijection not before.

**Comment by jahall** [comment]
Fixed in #1148

**Pull request closed without merging**
