### PR TITLE
name gaussian likelihoods

### PR DESCRIPTION
**Pull request by gdkrmr**
added name argument to `class Gaussian(Likelihood)`, this prevented storing and loading models to and from files. I am pretty sure that there are more of the same, but I am not familiar enough with the code base to point them out. See #689.

### CODE REVIEW

**Comment by gdkrmr** [comment]
what still does not work is saving and loading the same model in a single Python session

**Comment by awav** [comment]
Hi. `what still does not work is saving and loading the same model in a single Python session` can you elaborate what do you mean by _in single python session_?

**Comment by gdkrmr** [comment]
This is because you cannot create two tensors with identical names in the same tf session. It is possible to solve this with `defer_build`, see #689.

**Comment by awav** [comment]
What do you mean by "in single python session"? Is that your ipython notebook or terminal run? You could create models within different graph in that case. It doesn't make sense to store/restore models within same graph.
Also, I'm not sure what do you mean by saving models, because gpflow doesn't provide such feature at that moment. Yes, you can use tensorflow saver, but you need to be very careful about what exactly you are saving (graph can have more than just a model: optimizers and cetera) and for loading you have to use different graph.

**Pull request merged**
