### PR TITLE
Changed depreciated warnings

### PR DESCRIPTION
**Pull request by mathDR**
I went ahead and changed the depreciated initialize_all_variables() to the global_variables_initializer(). Also, I changed some depreciated max_iters and display in some of the tests.  Now when you run
```python
python setup.py test
```
you get almost no warnings

### CODE REVIEW

**Comment by jameshensman** [comment]
This is currently failing because we can't find `global_variables_initializer`.  travis is using python 3.5, tensorflow 0.11. Does this require tensorflow master?

**Comment by mathDR** [comment]
Sorry @jameshensman yes, currently I have python 2.7.12 and tensorflow 0.12.0-rc0.  Perhaps we can keep this around until you upgrade to tf master?

**Comment by jameshensman** [comment]
@mathDR what's the status of this PR on tf1.0? Note that GPflow now uses tf1.0, and @markvdw has been using tf1.0 for a while. Should I merge this or is it superceded?

**Comment by markvdw** [comment]
It's superceded, you can see 0 files changed in the tab above.

**Comment by mathDR** [comment]
Yep, superceded.  @markvdw Many eyes make for less work!  I think we can close this now.

**Comment by jameshensman** [comment]
Closing as this is superseded.

**Pull request closed without merging**
