### PR TITLE
link GPLVM documentation

### LINKED ISSUE #279: docs should include reference to GPLVM methods
Hi @alexisboukouvalas , 

You noted that the docs don't include a reference to the GPLVM yet, even though there is a notebook. 

The way to add the notebook to the docs is to modify doc/source/index.rst. It will be obvious how to add the notebook when you open the file :)

You could also modify doc/source/intro.rst, thich contains some description of the project, and what's included. Suggest you update this also. 

To build the docs, install the dependencies
```
pip install sphinx nbsphinx numpydoc
```
Then from the doc directory, type `make html` and the open doc/build/index.html

Once the edits are pushed to master, they will appear automatically within a few minutes on readthedocs.org. If you'd like access to GPflow on readthedocs.org, which will let you automatically build docs on branches, make an account there and I will give you access. 
James.

### PR DESCRIPTION
**Pull request by alexisboukouvalas**
In intro.rst we are already referring to the GPLVM notebook but neglected to add it to the documentation index.rst
This fixes #279  I have also created an account  on readthedocs.org (account alexisboukouvalas).
@jameshensman if you give me access, I can try to build the documentation on this branch as suggested in #279.

### CODE REVIEW

**Comment by alexisboukouvalas** [comment]
I also get a page not found (404) when I click on the regression notebook in the [documentation](https://gpflow.readthedocs.io/en/latest/intro.html). What is the right way to link to the notebook from the documentation?

**Comment by jameshensman** [comment]
The documentaion links work fine on readthedocs.org for me. Is it your local copy that's playing up?

The right way to link to the notebook is as you have done, which parses the notebook into html with some extra bits to incorporate it into the docs.

**Comment by alexisboukouvalas** [comment]
In https://gpflow.readthedocs.io/en/latest/intro.html when I click on the link to the regression notebook:
"For GP regression with Gaussian noise, it’s possible to marginalize the function values exactly: you’ll find this in GPflow.gpr.GPR. You can do maximum likelihood or MCMC for the covariance function parameters (*notebook*)." 
I get a page not found (404).

The link is: https://github.com/GPflow/GPflow/blob/master/notebooks/regression.ipynb
When I copy that link to my internet browser I also get a page not found.

I have a similar link from intro.rst to the GPLVM notebook.
sorry if I am being daft!

**Comment by jameshensman** [comment]
Looks great, thanks @alexisboukouvalas 

There was one hanging coreg_demo notebook that I moved from notebooks to the doc/notebooks directory.

**Comment by alexisboukouvalas** [comment]
thanks @jameshensman. Once the integration tests pass, we can merge this PR into master. I am glad to do it if you are happy with the changes or perhaps as I initiated the PR you would prefer to do the merge (I think that's the policy right? - we don't merge our own PRs?)

**Comment by jameshensman** [comment]
yep :)

**Pull request merged**
