### PR TITLE
changes to Autoflow to work when the graph gets reset

### LINKED ISSUE #61: autoflow fails after reset_default_graph
Sometimes it's necessary to reseat tensorflow's graph for memory reasons. This can be done with `tf.reset_default_graph()`. 

Problem is, this breaks all out AutoFlow functions! Here's a MWE:
```python
tf.reset_default_graph()
k = GPflow.kernels.Matern32(1)
X, Y = np.random.randn(2, 10, 1)
m = GPflow.gpr.GPR(X, Y, kern=k)
m.predict_f(m.X)
```

This is because the Autoflow constructor takes placeholders as arguments. After reset_default_graph, those placeholders are not on the same graph as everything else.  I'm going to propose a fix where we just give AutoFlow enough information to *make* the placeholders, not the placeholders themselves.

### PR DESCRIPTION
**Pull request by jameshensman**
Fixes #61

### CODE REVIEW

**Comment by jameshensman** [comment]
After working with @alexggmatthews , this branch now speeds up the tests dramatically (fixes also #67). Tests now take 4 minutes on my laptop and 8 minutes on the codeship server. 

Ready to merge!

**Comment by alexggmatthews** [comment]
@jameshensman are we rebased yet? I notice we now have 6 commits.

**Comment by jameshensman** [comment]
Phew that was a horrible rebase, should be ready to go now.

**Comment by alexggmatthews** [comment]
OK sorry to hear that. I really thing that squash.sh might be worth a look in future.

**Comment by jameshensman** [comment]
The squash script is okay, but doesn't let you drop commits, or leave in several commits: you have to squash everything into one.

**Comment by alexggmatthews** [comment]
OK.

**Comment by jameshensman** [comment]
phew! I thought you were rejecting my PR!

**Comment by alexggmatthews** [comment]
Nope. Friday afternoon slip - sorry! No harm done.

**Pull request merged**
