### PR TITLE
Fix SGPR upper bound for non zero mean functions

### PR DESCRIPTION
**Pull request by awav**

### CODE REVIEW

**Review by st-- — APPROVED** [review]
Woops, good catch! Thanks for this fix.

**Review by vdutor — APPROVED** [review]
It's pretty scary to think this type of bugs are still in the code... Was this code untested?

**Comment by st--** [comment]
> It's pretty scary to think this type of bugs are still in the code... Was this code untested?

Good point. There already was a test for the `upper_bound` implementation (tests/integration/test_method_equivalence) - it even has a mean fucntion in it, but it's initialized to zero and the test data is such that it remained close enough to zero that it didn't catch the numeric discrepancy...

**Comment by st--** [comment]
Please incorporate #1561 into this before merging so that we tighten up the test:)

**Pull request merged**
