### PR TITLE
Fixed optimiser options to be consistent with scipy

### PR DESCRIPTION
**Pull request by markvdw**
Small updates to code, keeping it up-to-date with scipy. Fixes https://github.com/GPflow/GPflow/issues/147.

I know it's slightly annoying to have changes in code interface, but it fixes inconsistencies between optimisers, and I think we should adhere to scipy's conventions.

### CODE REVIEW

**Comment by jameshensman** [comment]
Really nice. 

Suggestion: put a VisibleDeprecation warning in to help users switch. So when people pass in the old arguments ('max_iters' and 'display'), they get automatically converted to 'maxiter' 'and 'disp', but with a warning. Then in the next+1 version, we can remove the warning.

Since this changes the api, suggest also a minor version bump in _version.py

**Comment by markvdw** [comment]
Fixed.

**Comment by markvdw** [comment]
@jameshensman, I'm not exactly sure about how the coverage setup works, and before I start a string of commits to figure out the correct command, do you know how to exclude a block of code from the code coverage? I don't want to write a test for the deprecation warning, and the `#pragma nocover` that I saw elsewhere in the code doesn't seem to be doing the trick.

**Comment by jameshensman** [comment]
hi Mark, 

the `#pragma: no cover` *does* work, but not when I typed `#pragma: no-cover`, which is a bug.

in param.py, I correctly typed `#pragma: no cover` at line 762: this doesn't get covered. But at line s 255 and 396, I incorrectly added the hyphen. 

You can find other things that we excuse from coverage in `GPflow/.coveragerc`

**Pull request merged**
