### PR TITLE
Final pass over GPflow notebooks

### PR DESCRIPTION
**Pull request by akhayes**
Various minor edits/typo fixes, plus revert UK spelling to US as previously discussed.

See https://prowlerio.atlassian.net/browse/PTKB-7779

### CODE REVIEW

**Comment by st--** [comment]
Note: would be good if we could apply the same changes to the `develop-2.0` branch (which will be The Future(tm), once we've managed to squash all remaining bugs...), not sure if `git cherry-pick` would work though ?

**Comment by st--** [comment]
Hi @akhayes, I'm afraid this PR got caught by the move to gpflow2 -- any chance you could fix up this PR to cleanly apply on top of now-current `develop` (previously `develop-2.0`)?

**Comment by akhayes** [comment]
> Hi @akhayes, I'm afraid this PR got caught by the move to gpflow2 -- any chance you could fix up this PR to cleanly apply on top of now-current `develop` (previously `develop-2.0`)?

I thought I'd sorted this out with Artem the other day :-(
But yes I can fix - I currently have a fork of GPflow/GPflow at akhayes/GPflow, what do I need to do to make sure that I am working from the right version?

**Comment by st--** [comment]
are these changes the same as in #1146 ? (in which case, can this PR be closed in favour of #1146?)

**Comment by st--** [comment]
Closed in favour of #1165

**Pull request closed without merging**
