### PR TITLE
Vgp as svgp

### PR DESCRIPTION
**Pull request by hughsalimbeni**
The vgp after opper and archambeau is more parameter efficient than svgp with X=Z, but suffers from non-convexity #389. This PR retains the old vgp as `VGP_opper_archambeau`, but replaces `VGP` with the (whitened) `SVGP` model with X=Z, with unnecessary computation removed.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
So the issue in #389 was diagnosed as resulting from non-convexity in the end? Perhaps I missed a conversation. If so do we know that svgp doesn't suffer from the same problem? I think I remember Emtiyaz Khan writing something on this topic.

**Comment by hughsalimbeni** [comment]
[Khan, Mohamed and Murphy](https://papers.nips.cc/paper/4535-fast-bayesian-inference-for-non-conjugate-gaussian-process-regression.pdf) analysed the Opper/Archambeau parametrisation and found it non-convex even in the case of a single point (section 5, final two paragraphs). Their convex coordinate ascent scheme shows improved results over Opper/Archambeau parametrisation. Further, [Challis and Barber](http://proceedings.mlr.press/v15/challis11a/challis11a.pdf) looked at the lower triangular parametrisation and showed that the optimisation is convex for Bayesian linear models. 

I'd suggest that the saving in parameters is insufficiently useful, given that the optimisation is harder and there aren't any computation savings. 

Experimentally:

```
N = 200
rng = np.random.RandomState(0)
X = rng.rand(N, 1)*10
Y = np.sin(X) + 0.9 * np.cos(X*1.6) + rng.randn(*X.shape) * 0.8

m1 = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.RBF(1),
                    mean_function=GPflow.mean_functions.Constant())
m2 = GPflow.vgp.VGP(X, Y, GPflow.kernels.RBF(1), likelihood=GPflow.likelihoods.Gaussian(),
                    mean_function=GPflow.mean_functions.Constant())
m3 = GPflow.vgp.VGP_opper_archambeau(X, Y, GPflow.kernels.RBF(1), likelihood=GPflow.likelihoods.Gaussian(),
                    mean_function=GPflow.mean_functions.Constant())
print(m3)
Ls = []
for m in [m1, m2, m3]:
    m.optimize()
    Ls.append(m.compute_log_likelihood()) 
print(Ls[1:] - Ls[0])  # [ -4.85780620e-06  -4.30471057e-03]
```

**Comment by alexggmatthews** [comment]
Ok @hughsalimbeni sounds reasonable to me.

**Comment by jameshensman** [comment]
I merged the internal dup.

**Pull request closed without merging**
