### PR TITLE
Allow Lm to be passed-in to conditionals/util.py

### PR DESCRIPTION
**Pull request by nfergu**
## PR content:

* [Title](#title)
* [Description](#description)
* [Minimal working example](#minimal-working-example)

### Title

Allow `Lm` to be passed into utility functions for computation of conditionals. 

### Description

This PR allows the utility methods in `conditionals/util.py` to use pre-computed values for `Lm`. This allows the performance of, for example, prediction to be improved by passing these pre-computed values into the conditionals calculation, instead of calculating these each time.

This is a more minimal version of #1507, requiring many fewer changes to GPflow (at the expense of slightly more code in my model -- see the example below).

### Minimal working example

Here is a rough example of how I would use the new `base_conditional` in my model. This improves prediction time by about 10x.

```
class MySVGP(SVGP):

    def __init__(self, kernel, likelihood, inducing_variable, *, mean_function=None,
                 num_latent_gps: int = 1, q_diag: bool = False, q_mu=None, q_sqrt=None,
                 whiten: bool = True, num_data=None):
        super().__init__(kernel, likelihood, inducing_variable, mean_function=mean_function,
                         num_latent_gps=num_latent_gps, q_diag=q_diag, q_mu=q_mu, q_sqrt=q_sqrt,
                         whiten=whiten, num_data=num_data)
        self._Kmm_for_prediction = None  # [M, M]
        self._Lm_for_prediction = None  # [M, M]

    def train(self):
        # Do training here...
        self._Kmm_for_prediction = covariances.Kuu(self.inducing_variable,
                                                   self.kernel, jitter=default_jitter())
        self._Lm_for_prediction = tf.linalg.cholesky(self._Kmm_for_prediction)

    def predict_f(self, Xnew: InputData, full_cov=False, full_output_cov=False) -> MeanAndVariance:
        if self._Kmm_for_prediction is None or self._Lm_for_prediction is None:
            raise ValueError('Kmm or LM is not set. Use the train method to train the model.')
        mu, var = self.compute_conditional(Xnew, full_cov, full_output_cov)
        return mu + self.mean_function(Xnew), var

    def compute_conditional(self, Xnew, full_cov, full_output_cov):
        Kmn = Kuf(self.inducing_variable, self.kernel, Xnew)  # [M, N]
        Knn = self.kernel(Xnew, full_cov=full_cov)
        fmean, fvar = base_conditional(
            Kmn, self.Kmm, Knn, self.q_mu, full_cov=full_cov, q_sqrt=self.q_sqrt, white=self.whiten
        )  # [N, R],  [R, N, N] or [N, R]
        return fmean, expand_independent_outputs(fvar, full_cov, full_output_cov)
```

### CODE REVIEW

**Comment by nfergu** [comment]
@st-- I've opened this as a more minimal alternative to #1507. This involves very few changes GPflow. What do you think?

**Comment by st--** [comment]
Hi @nfergu, I thought about this and discussed it with @markvdw. In some sense this is a band-aid for a larger underlying issue (and also related to a previous discussion about introducing a separate, decoupled posterior object that allows more efficient predictions.

The code you changed doesn't actually use `Kmm` directly other than to compute the Cholesky: to avoid having to pass in both `Kmm` _and_ `Lm`, with the former not getting used at all, and wondering whether we should ensure consistency between the two, we were thinking it might make more sense, instead, to introduce an extra flag `Kmm_is_cholesky`, defaulting to False, and then
```python
    Lm = Kmm if Kmm_is_cholesky else tf.linalg.cholesky(Kmm)
```

What do you think about that?

**Comment by nfergu** [comment]
Thanks for your comments @st-- 

> Hi @nfergu, I thought about this and discussed it with @markvdw. In some sense this is a band-aid for a larger underlying issue (and also related to a previous discussion about introducing a separate, decoupled posterior object that allows more efficient predictions.

I agree that it is a band-aid. I'm also vaguely aware of the discussion around a separate posterior object. We need a solution for this in the fairly near future though, so it may be that a band-aid is the only realistic solution.  

> 
> The code you changed doesn't actually use `Kmm` directly other than to compute the Cholesky: to avoid having to pass in both `Kmm` _and_ `Lm`, with the former not getting used at all, and wondering whether we should ensure consistency between the two, we were thinking it might make more sense, instead, to introduce an extra flag `Kmm_is_cholesky`, defaulting to False, and then
> 
> ```python
>     Lm = Kmm if Kmm_is_cholesky else tf.linalg.cholesky(Kmm)
> ```
> 
> What do you think about that?

I'm happy with that solution if you are. I guess an alternative could be for the conditional computation function to take a "cholesky calculation function" argument, which is a function that takes `Kmm` as its argument and defaults to `tf.linalg.cholesky(Kmm)`, but which the user could override to just return `Kmm`? I guess this wouldn't actually enforce that `Lm` is consistent with `Kmm` though, since the caller could return whatever they like from this function. 

I don't feel strongly about either approach, so feel free to advise as to which you prefer.

**Comment by marcoadurno** [comment]
Hi @nfergu,

I've been thinking of doing something similar because I have similar requirements (fast predictions). Are you running predictions from a TF saved_model or via aot/tfcompile? 

I'm doing the latter and I'm observing something really odd in term of runtime performance. Basically even if `Lm` is pre-computed the prediction time doesn't drop. I'll try and share a minimum working example this week so that you can have a look as well, just to double check that I'm not doing anything silly. Unless I'm doing something really silly it's most likely a TF issue.

Best Regards,

Marco

**Comment by nfergu** [comment]
Hi @marcoadurno.

> I've been thinking of doing something similar because I have similar requirements (fast predictions). Are you running predictions from a TF saved_model or via aot/tfcompile?

I'm using a TF savedmodel. With this I get around a 10x speed-up by computing `Kmm` and `Lm`. I haven't tried via aot/tfcompile I'm afraid. I'd be happy to look at your example and see if I can spot any problems though.

**Comment by nfergu** [comment]
Superceded by #1528

**Comment by marcoadurno** [comment]
> Hi @marcoadurno.
> 
> > I've been thinking of doing something similar because I have similar requirements (fast predictions). Are you running predictions from a TF saved_model or via aot/tfcompile?
> 
> I'm using a TF savedmodel. With this I get around a 10x speed-up by computing `Kmm` and `Lm`. I haven't tried via aot/tfcompile I'm afraid. I'd be happy to look at your example and see if I can spot any problems though.

Hi @nfergu ,

We have done some further work with aot and identified two possible issues with TensorFlow. 

One is a possible bug in the code-gen step: [41938](https://github.com/tensorflow/tensorflow/issues/41938)
The other is related to the performance of the generated code for `triangular_solve`: [41940](https://github.com/tensorflow/tensorflow/issues/41940)

Regarding [41938](https://github.com/tensorflow/tensorflow/issues/41938) I don't understand how on earth the whole computational graph generated by GpFlow works (we routinely compile it via aot and it works), but we'll first try to get to the bottom of this issue and then we'll see.

Best Regards,

Marco

**Pull request closed without merging**
