### PR TITLE
Periodic kernel

### PR DESCRIPTION
**Pull request by alexisboukouvalas**
Added support for periodic kernel as described in Equation (47) of 
    D.J.C.MacKay. Introduction to Gaussian processes. In C.M.Bishop, editor, Neural Networks and Machine Learning, pages 133--165. Springer, 1998.
Added single unit test test_kerns/TestPeriodic
All tests pass.

In future work, I hope to add support for Bayesian GPLVM to use this kernel.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
Hi @alexisboukouvalas hope you all good with you. This seems to me like the sort of thing we should have. 

I'd be happy to help with the merging. 

I remember James Lloyd was at one point playing with cos(w(x-x')) as a kernel. Do we know what the relevant merits of the two variants are? Maybe we ought to have both. 

@jameshensman do you have an opinion?

**Comment by markvdw** [comment]
Doesn't the cosine kernel only produce exact cosines? While the periodic produces a sqexp constrained to repeat over some interval.

**Comment by alexggmatthews** [comment]
Thanks @markvdw , @alexisboukouvalas sorry for the red herring.

**Comment by jameshensman** [comment]
And we already have the Cosine kernel :)

**Comment by alexisboukouvalas** [comment]
Thank you all for your feedback.
Thanks @jameshensman I will have a look later on at implementing the subspace-projection kernel.
I will also try the Psi functons for BGPLVM for the periodic kernel.

Have a good weekend everybody. Let me know if you would like me to change anything for this pull request.

**Comment by jameshensman** [comment]
Just looking at this now

**Pull request merged**
