### PR TITLE
Fix MLP acos numerics

### PR DESCRIPTION
**Pull request by mrksr**
This PR accompanies #409.

Adding a jitter to the `tf.acos`-operation fixes the gradient problem, but introduces a new one: Now, the kernel does not pass the correctness-tests anymore. We can make the closness-test more lenient, but I wanted to ask for your opinion: Using a jitter larger than `1e-10` results in the diagonal of `kern.K(X)` not being equal to `1` anymore. Will this be a problem?

### CODE REVIEW

**Comment by markvdw** [comment]
I wouldn't technically use the jitter_level here, as the numerical issue is different to where jitter_level is usually used (i.e. in inversions). I expect that a very small rescaling should be enough. I found that the offending value was essentially a single machine epsilon above 1.

I suggest we just take the smallest possible value for now, and see whether it causes any problems in the future. If it does, we know where the cause is.

**Comment by mrksr** [comment]
Okay, I now chose the smallest power of ten for which the tests still pass. This seems to work for both `float32` and `float64` interestingly. But I suspect this number will have to be tweaked a little bit at some point.

**Comment by mrksr** [comment]
So I have now chosen this jitter to be as close to the `float64` machine epsilon as possible. And the `TestArcCosine`-tests all still pass when I change the float_type to `float32` in `gpflowrc`. The complete test-suite does not, but this is due to the fact that `float64` is hardcoded at several places in `test_kerns.py`. If I force `float32`-calculations, the correctness-tests no longer pass if I choose a jitter which prevents the NaNs (`1e-7`).

Should we choose the jitter dependent on the float type and live with the fact that using `float32`, the diagonal will not be equal to one? If so, is there a better way than this:
```python
if float_type is tf.float32:
    jitter = 1e-7
else:
    jitter = 1e-15
```

**Comment by markvdw** [comment]
@jameshensman: How do you usually move a PR into an "in-house" PR that gets tested and can get merged?

**Comment by jameshensman** [comment]
make a new local branch, pull the remote onto it, and push to GPflow/origin. There are some helpful hints under 'view command line instructions' below. Here, they suggest:

```bash
git checkout -b mrksr-fix-mlp-acos-numerics master
git pull https://github.com/mrksr/GPflow.git fix-mlp-acos-numerics
```
Now fix any merge conflicts. Hopefully there are none. 

But then, instead of pushing to master like they suggest (which is disabled in GPflow), you should do 

```git push --set-upstream origin mrksr-fix-mlp-acos-numerics```

to push your new branch to GPflow. Then the tests should run and you can merge.

**Comment by mrksr** [comment]
Thanks for the quick merge :). So we need to keep in mind that currently the kernel will not work with `float32`.

**Pull request closed without merging**
