### PR TITLE
Unblacklist some notebooks so tests can run and delete the monitoring

### PR DESCRIPTION
**Pull request by condnsdmatters**
notebook, since it is not needed in gpflow2

### CODE REVIEW

**Comment by condnsdmatters** [comment]
This notebook was deleted per discussion with @awav

**Comment by awav** [comment]
@condnsdmatters you need to remove settings notebook as well.

**Comment by condnsdmatters** [comment]
Looks like the natural gradients test is failing - will inspect

**Comment by awav** [comment]
@condnsdmatters , it is fixed.

**Pull request merged**
