### PR TITLE
Verbosity flags for optimisation and compilation now used

### PR DESCRIPTION
**Pull request by markvdw**
Ready to be merged.

### CODE REVIEW

**Comment by jameshensman** [comment]
Hmm, coverage fails because the print statements don't get tested. We could change the coveragerc to ignore all print statements? Writings tests for print statements seems overkill.

**Comment by jameshensman** [comment]
woah, that's a bug in gpmc.py

```python
 L = tf.cholesky(K) + eye(tf.shape(self.X)[0])*settings.numerics.jitter_level
```

should be 
```python
 L = tf.cholesky(K + eye(tf.shape(self.X)[0])*settings.numerics.jitter_level)
```

**Comment by jameshensman** [comment]
jitter also gets used in sgpr.py, conditionals.py, svgp.py

**Comment by markvdw** [comment]
Should tests also depend on the jitter level?

**Comment by jameshensman** [comment]
I thinks tests should pass with the gpflowrc that we provide. 

If users want to go off-piste and change the settings, that's fine, but running the tests for every permutation of gpflowrc is not feasible.

**Pull request merged**
