### PR TITLE
Fixed AutoFlow sharing `self.tf_args` between different instances

### PR DESCRIPTION
**Pull request by markvdw**
Issue discussed here https://github.com/GPflow/GPflow/issues/85.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@jameshensman do you mind having a look at this one, please? I think you have done more AutoFlow than me. Thanks, A

**Comment by jameshensman** [comment]
Yeah, this is clearly the right thing to do, nice work. 

Line 207 `in model.py` deletes the autoflow graphs when the model is flagged to be recompiled. Could you do the same for the tf_args, please?

**Comment by jameshensman** [comment]
Oh, and please add the failure-case you specified in #85 as a test in `testing/test_autoflow.py`. I'm happy to help if it's not clear how it should work.

**Comment by markvdw** [comment]
If the graph is deleted then `tf_args` is automatically recreated, so it shouldn't make a difference. I instinctively feel like it's best to rely purely on the existence of the graph to indicate whether AutoFlow is stale, rather than deleting every variable we need to store. This can be a hard thing to keep consistent.

I've added a test which passes with the changes but fails on master.

**Comment by jameshensman** [comment]
okay, that's fine with me. Just merging in master and adding a docstring to your test, then I'll accept this PR if the build/coverage tests pass.

Good test btw, nice and succinct.

**Pull request merged**
