### PR TITLE
Travis py3

### PR DESCRIPTION
**Pull request by jameshensman**
edits to travis.yml to get tests running on python 3

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@jameshensman thank you for your pull request. My only question is do we want code coverage on both python 2 and 3? I'm not sure.

**Comment by jameshensman** [comment]
I don't see that it would add anything.

**Comment by alexggmatthews** [comment]
@jameshensman OK I agree. I was slightly confused. I see 5 different "successful checks" two of them are coverage tests. What is the difference between them?

**Comment by jameshensman** [comment]
If I understand correctly, travis/push tests the pushed code. travis/pr tests the code after it's been merged into master. So I guess if the pr is up to date with master, they will necessarily be identical.

https://docs.travis-ci.com/user/pull-requests

**Comment by alexggmatthews** [comment]
OK thanks that explains some of what I see but there is a question which I think is orthogonal to this PR which is: "why is coveralls reporting the code coverage when we don't use it on the front page any more?"

**Comment by jameshensman** [comment]
I think we left coveralls in because we were still transitioning around between services. It's easy to remove it...

**Comment by alexggmatthews** [comment]
OK I'll add an issue to remind us to do it. A good end to a long day. Thanks and have a good weekend.

**Pull request merged**
