### PR TITLE
Added cholesky decomposition with jitter

### LINKED ISSUE #64: Sample from model
What would be the preferred way to sample from a GP with mean function/compositional kernel? I tired the various sample/predict and also the evalK() from #63 but I can't make it work.

### PR DESCRIPTION
**Pull request by PabloLeon**
Heavily based on the GPy implementation. Should fix #64.

### CODE REVIEW

**Comment by jameshensman** [comment]
Hi @PabloLeon 

Thanks for this! 

Unfortunately, I think there's an issue: tf.cholesky will never raise an error, because that only constructs the graph to compute the Cholesky. Numerical errors that occur during the Cholesky decomposition will occur only once the graph is executed.

**Comment by PabloLeon** [comment]
@jameshensman yes you are right.
I could delete the except block and simply increase the jitter with num_tries?

**Comment by mathDR** [comment]
If the number of tries exceed a predefined amount, you could replace the decomposition with the closest non-singular matrix. Probably should warn the user if you do this though. Let me know if you are interested and I could do a PR.

**Comment by PabloLeon** [comment]
@mathDR sounds good to me!

**Comment by mathDR** [comment]
After thinking about this for a while, I think the idea of adding jitter is the way to go.  (Instead of replacing with the closest non-singular matrix -- in fact, there is no *closest* as any nonzero perturbation will lead to a nonsingular matrix).  

The issue will be with the condition number of the original covariance matrix:  if it is high, then there may be numerical problems.  Maybe the answer is to report the condition number of the matrix and give a warning that the original covariance is ill conditioned?

**Comment by jameshensman** [comment]
Adding jitter certainly work well for GPy. This issue here is that you'd
have to implement the detection of the CN *inside* the tensorflow kernel.

**Comment by PabloLeon** [comment]
@jameshensman any advice on how to detect it? Alternatively, can we just inform the user about the added jitter at graph execution and increase the number of attempted iterations?

**Comment by PabloLeon** [comment]
Any news on this? Is the approach in #72 the way to go/ shall I close this?

**Comment by alexggmatthews** [comment]
Long term I'm not sure it has been conclusively resolved yet. It has been proving tricking to get a clean solution so far. @jameshensman perhaps we should have another think about this thread?

In the shorter term #74 makes it possible to add white noise that is constrained not to grow too large which may well help in many situations put is not a perfect solution.

**Comment by PabloLeon** [comment]
@alexggmatthews Thanks! My models are created automatically, i.e. I have very little control and can't add white noise as needed but would need to catch the singularity issues automatically (by adding jitter/adding white noise kernels). 
So either I need to catch the error after the graph is executed (not sure how to do this automatically) or "predict" the singularity before tf creates the graph? Any advice on how/where to best integrate this functionality (sorry still struggling with tensorflow etc.)?

**Comment by jameshensman** [comment]
Hey @PabloLeon 

How is numerical stability in GPflow for you these days, has it improved?

There was a small fix that went in recently that prevented parameters becoming numerically zero, and this fixed problems for several people. If your use case is also fixed, perhaps we can close this?

**Comment by PabloLeon** [comment]
@jameshensman Yes it looks better now! Thanks for the fixes! We can close/delete this PR.

**Comment by jameshensman** [comment]
Great! I'm pleased it's working well. If there are still issues, I guess they will be separate from those already fixed, so please do open up a new bug report describing them if so.

**Pull request closed without merging**
