### PR TITLE
Remove need for bespoke pip package

### PR DESCRIPTION
**Pull request by alexggmatthews**
TensorFlow 0.9.0 has been released which means we no longer need our own pip package. I have updated the readme with new instructions.

### CODE REVIEW

**Comment by jameshensman** [comment]
Could you update the codeship calls so that we're testing against this too, please?

**Comment by alexggmatthews** [comment]
Ok I've lost track. Where are the codeship calls now? I can only see a travis file.

**Comment by jameshensman** [comment]
https://codeship.com/projects/147609/configure_tests

**Comment by alexggmatthews** [comment]
OK done and waiting for tests.

**Comment by alexggmatthews** [comment]
@jameshensman looks like the coverage has decreased. Do you know of a way to get at the diff of the coverage using coveralls? Happy to look it up if you don't have a quick answer.

**Comment by jameshensman** [comment]
No, sorry, I don't know off-hand.

**Comment by alexggmatthews** [comment]
@jameshensman Turns out we no longer need the float32 hacks with this version of TensorFlow . Now that I have removed them the Test Coverage is fine.

**Pull request merged**
