### PR TITLE
adding value property to Param class

### PR DESCRIPTION
**Pull request by jameshensman**
As discussed in #81

### CODE REVIEW

**Comment by markvdw** [comment]
Looks good James, did you just want me to sign off on the merge? Or did you also want me to look into the issue of setting `_needs_recompile` on a new `Param` object assignment?

Currently, I don't think assigning a new `Param` object will trigger a recompile. What would be a good way to do this? I can only think of the solution of writing a getter and setter for each attribute, which may be a bit verbose...

**Comment by jameshensman** [comment]
Well, now that you mention it, perhaps this would be a good opportunity to fix that. Working on it now!

**Comment by jameshensman** [comment]
Okay, I added a functionality so that when you replace a Param with a new Param, 

1) The old parameter gets unlinked from the tree (i.e. it can no longer reference a 'parent')
2) The new parameter gets linked to the tree (this happened anyway)
3) The model gets told to recompile (if there is a model to recompile, of course)

**Comment by alexggmatthews** [comment]
@jameshensman @markvdw What will be the behaviour of the functionality with arrays. Do we want to make .value give a copy? Something to think about.

**Comment by jameshensman** [comment]
I think we do, otherwise if the user does something interesting to the result, it will change the model. Example (using curent code):

```python
m = GPflow.model.Model()
m.p = GPflow.param.Param(np.arange(3))
# m.optimize, whatever

result = m.p.value
print m

# model.p transform:(none) prior:None
# [ 0.  1.  2.]

result += 4
print m
# model.p transform:(none) prior:None
# [ 4.  5.  6.]
```

**Comment by markvdw** [comment]
I really like the fix to setting the `_needs_recompile` flag. Essentially this relies on the fact that `Model` inherits from `Param` right? Hadn't looked at this code yet, but I think it's really elegant.

Ok, so the current situation as I see it:
- Can read parameter values using `Param.value`
- Can set the values of the parameter using `.param_name = some_value` (does not trigger re-compilation)
- Can re-set the whole parameter by assigning a new `Param` object (triggers re-compilation)

Looks ideal to me! Just needs fixing of the typo `FailIf` in the test. Shouldn't that be `failIf`?

Also, `failIf` seems to be deprecated. It should be `assertFalse` [https://docs.python.org/2.7/library/unittest.html].

**Comment by markvdw** [comment]
Ok I uploaded a small fix. I couldn't merge into master though due to some conflicts. Could someone else look at this? I don't want to erase anybody else's changes.

**Comment by jameshensman** [comment]
Taking a look now.

**Comment by jameshensman** [comment]
Turns out git doesn't like merging things if you rename methods. All fixed now.

**Pull request merged**
