### PR TITLE
Binned poisson

### PR DESCRIPTION
**Pull request by mathDR**
Added a BinnedPoisson Likelihood.

Started a coal demo notebook to show it working with "real data" (replicating the coal demo from the paper "MCMC for Variationally Sparse Gaussian Processes" by Hensman, et.al.)

All tests pass.

### CODE REVIEW

**Comment by mathDR** [comment]
There are some garbage files I just deleted them and pushed changes

**Comment by alexggmatthews** [comment]
@mathDR Thanks for the PR. Nice to replicate those experiments. 

I'm personally not sure we need a complete new likelihood for the binning functionality. Is there maybe a way to use more of the existing Poisson code?

Also the PR seems to change 12 files at the moment. Are all of these strictly necessary?

**Comment by mathDR** [comment]
@alexggmatthews The functionality supersedes the current Poisson likelihood.  In particular, you can recover the current Poisson likelihood by setting the binsize in BinnedPoisson to 1.

As for the files, the only ones needed are the Likelihood.py and the test_likellihoods.py.  The others were either mistakenly pushed or to support the coal demo notebook (the coal.csv file in data/ for instance).

Should I delete this PR and submit another with just the bare bones new likelihood?

**Comment by jameshensman** [comment]
Perhaps overwrite the Poisson likelihood with the binned expressions, and make the default bin size 1?

**Comment by mathDR** [comment]
@jameshensman That is exactly what I was thinking.  So the name of the likelihood won't change.  It will still be called Poisson(), just with an added parameter of binsize.

I will do that.

**Comment by mathDR** [comment]
Okay, I pared down the PR to only have changed Poisson() in likelihood.py to allow for a binsize.  All tests pass locally on my machine.

**Comment by jameshensman** [comment]
Thanks again for this PR, @mathDR . A few comments before merging:

1) Please add a docstring to Poisson explaining what binsize does, and noting the connection to the LGCP. 

2) I don't think there are significant changes to kernels.ipynb or mcmc.ipynb. If these are updated, please comment as to how, else revert. 

3)  Please remove "rouses_nopprices.ipynb" or bring it in line with the rest of the documentation. 

Thanks!

**Comment by mathDR** [comment]
@jameshensman Take a look at the docstring.  I don't know if that is expressive enough.  The other comments are updated too.

**Comment by alexggmatthews** [comment]
@mathDR @jameshensman it would be good to get this one in or close it. As far as I can tell it is good to go apart from some unnecessary notebook changes?

**Comment by mathDR** [comment]
@alexggmatthews I think it is good?  Any of the notebook changes can be discarded.

**Comment by jameshensman** [comment]
discarded the notebook changes and improived the docstring in the internal PR #464

**Pull request closed without merging**
