### PR TITLE
Allow conditionals to be computed based on pre-computed Kmm and Lm

### PR DESCRIPTION
**Pull request by nfergu**
## PR content:

* [Title](#title)
* [Description](#description)

### Title

Allow conditionals to be computed based on pre-computed `Kmm` and `Lm`

### Description

This PR allows conditionals to be computed based on pre-computed values for `Kmm` and `Lm`. This allows the performance of, for example, prediction to be improved by passing these pre-computed values into the conditionals calculation, instead of calculating these each time. 

I can add some tests if you think this is a reasonable approach.

### CODE REVIEW

**Comment by st--** [comment]
Hi @nfergu , you need to run the black formatter (`make format`). I'm mildly concerned about the option of passing in both `Kmm` *and* `Lm` that aren't consistent with each other. I'm a bit more concerned about this only being available in some specific conditionals, not as a whole.

What would it take to actually include this potential speed-up in the code?
Lack of "caching" of tensors is actually a bigger issue.... :/

**Comment by nfergu** [comment]
Thanks for your comments @st-- 

> Hi @nfergu , you need to run the black formatter (`make format`). 

Done!

> I'm mildly concerned about the option of passing in both `Kmm` _and_ `Lm` that aren't consistent with each other. 

This occurred to me also, but I couldn't think of a way of enforcing this without a significant refactor of the conditionals code.

This also relies on the caller of these functions knowing the correct way to calculate `Kmm` and `Lm` (and therefore knowing which function the call will actually be dispatched-to in the end), which also seems not ideal, but again I can't think of a way round this without a major refactor. 

> I'm a bit more concerned about this only being available in some specific conditionals, not as a whole.

I have hopefully addressed this now. I hadn't realised there were so many functions to calculate conditionals! 
 
> What would it take to actually include this potential speed-up in the code?

I was thinking that my model would look something like this:

```
class MySVGP(SVGP):

    def __init__(self, kernel, likelihood, inducing_variable, *, mean_function=None,
                 num_latent_gps: int = 1, q_diag: bool = False, q_mu=None, q_sqrt=None,
                 whiten: bool = True, num_data=None):
        super().__init__(kernel, likelihood, inducing_variable, mean_function=mean_function,
                         num_latent_gps=num_latent_gps, q_diag=q_diag, q_mu=q_mu, q_sqrt=q_sqrt,
                         whiten=whiten, num_data=num_data)
        self._Kmm_for_prediction = None  # [M, M]
        self._Lm_for_prediction = None  # [M, M]

    def train(self):
        # Do training here...
        self._Kmm_for_prediction = covariances.Kuu(self.inducing_variable,
                                                   self.kernel, jitter=default_jitter())
        self._Lm_for_prediction = tf.linalg.cholesky(self._Kmm_for_prediction)

    def predict_f(self, Xnew: InputData, full_cov=False, full_output_cov=False) -> MeanAndVariance:
        if self._Kmm_for_prediction is None or self._Lm_for_prediction is None:
            raise ValueError('Kmm or LM is not set. Use the train method to train the model.')
        q_mu = self.q_mu
        q_sqrt = self.q_sqrt
        mu, var = conditional(
            Xnew,
            self.inducing_variable,
            self.kernel,
            q_mu,
            q_sqrt=q_sqrt,
            full_cov=full_cov,
            white=self.whiten,
            full_output_cov=full_output_cov,
            Kmm=self._Kmm_for_prediction,
            Lm=self._Lm_for_prediction
        )
        # tf.debugging.assert_positive(var)  # We really should make the tests pass with this here
        return mu + self.mean_function(Xnew), var
```

I realise all of this is a bit kludgy, and I'm not particularly happy with it, but we need _some_ way of improving the prediction performance and I don't have any better ideas.

> Lack of "caching" of tensors is actually a bigger issue.... :/

Well, ideally TensorFlow would figure out that it doesn't actually need to compute these values each time and just cache them. I know @awav didn't looked into using TensorFlow's graph optimisations but didn't have any luck so far. Hence this PR.

**Comment by markvdw** [comment]
An alternative would be to rely on the multiple dispatch to do this. You could define a custom feature `PrecomputedInducingPoints` or something, and then have a custom conditional that takes precomputed matrices. You can make the conditional do whatever you want, and you wouldn't have to modify GPflow at all.

**Comment by nfergu** [comment]
> An alternative would be to rely on the multiple dispatch to do this. You could define a custom feature `PrecomputedInducingPoints` or something, and then have a custom conditional that takes precomputed matrices. You can make the conditional do whatever you want, and you wouldn't have to modify GPflow at all.

Thanks for your comments @markvdw. If I understand you correctly, I think this would work, but I'm concerned that I'd end up duplicating lots of code.

Thinking about it though, if I changed only the functions in `conditionals/util.py` to accept `Lm`, this would be a very minimal change to GPflow, and would enable me to create a custom conditional without duplicating too much code. I'll give that a try and see how it looks.

**Comment by nfergu** [comment]
I've opened #1514 as a more minimal version of this. Closing this PR

**Pull request closed without merging**
