### PR TITLE
Added constant kernel

### PR DESCRIPTION
**Pull request by markvdw**
A constant kernel as referenced in https://github.com/GPflow/GPflow/issues/40.

### CODE REVIEW

**Comment by jameshensman** [comment]
Nice work @markvdw , but we already have this kernel!  I call it the Bias kernel, following Neil's naming convention.

If we want to cover both naming conventions (I'm happy to), then perhaps a cleaner solution is

```python
class Constant(Bias):
    pass
```
This has the advantage that the naming of the constant in the model will be constant, i.e.

```python
k = GPflow.kernels.Linear(1) + GPflow.kernels.Constant(1)
m = GPflow.gpr.GPR(X, Y, kern=k)
m.kern.constant.variance = 7.3  # for example
```

**Comment by markvdw** [comment]
Hah! I completely missed that! I interpreted Alex's comment on a constant kernel being feasible as it not existing yet.

I would err on only keeping one naming convention and class for a particular functionality. It probably causes more confusion than it's worth to have two names for the same thing.

**Comment by jameshensman** [comment]
Right, but I kind of prefer Constant to Bias!

**Comment by markvdw** [comment]
Me too, as it was the name I was trying to find in `kernels.py`. I would vote to change it to constant :) But I'd leave the decision up to you and Alex.

**Comment by jameshensman** [comment]
@alexggmatthews , do you have any preference for the naming of this kernel?

**Comment by alexggmatthews** [comment]
No.

**Comment by jameshensman** [comment]
So I fixed this by adding a Constant class, and was then confused because pushes to  my constant_kernel branch wouldn't show up here. Now that's I've pushed to constant-kernel, I think we're ready to merge.

 @alexggmatthews , could you take a quick  look when you have time?

**Comment by alexggmatthews** [comment]
@jameshensman push issue not your fault I don't think. GitHub are "investigating reports of delayed notifications and delayed inbound commit processing."

**Comment by jameshensman** [comment]
Oh, It was my fault. note the hyphen/underscore discrepancy! :)

**Pull request merged**
