### PR TITLE
Added a function evaluation counter

### PR DESCRIPTION
**Pull request by markvdw**
I thought it would be good to have a function evaluation counter in `Model`, for profiling purposes.

### CODE REVIEW

**Comment by jameshensman** [comment]
Don't we get this in the return structure of the optimizer?

**Comment by markvdw** [comment]
Yes we do, but:
- It's hard to keep track if you do multiple consecutive optimisation runs.
- You don't get it if you terminate the optimisation early (e.g. using a KeyboardInterrupt).
- The information is lost if you pickle the object.

**Comment by jameshensman** [comment]
Oaky. But I think it should be called `feval_counter` or `num_fevals`.

**Comment by markvdw** [comment]
Done.

**Comment by markvdw** [comment]
I think this is ready to be merged. I added a small test for the counter as well.

**Pull request merged**
