### PR TITLE
Fix SGPR docstring

### PR DESCRIPTION
**Pull request by st--**
Unfortunately, the "_with_posterior"-docstring overwrote, instead of extending, the original SGPR docstring.

### CODE REVIEW

**Review by jesnie — APPROVED** [review]
LGTM

**Comment by st--** [comment]
@jesnie any idea why the docs-test build

**Comment by jesnie** [comment]
> @jesnie any idea why the docs-test build fails?

There was a bad release of a library we depend on. It should be fixed now.
For more details see https://github.com/GPflow/GPflow/pull/1990

**Comment by st--** [comment]
It's still failing @jesnie :cry:

**Comment by st--** [comment]
finally!

**Pull request merged**
