### PR TITLE
Improve nomenclature (issue #504)

### PR DESCRIPTION
**Pull request by st--**
As discussed in issue #504, this PR aims to improve the nomenclature of GPflow.

Any additional thoughts/suggestions, please comment.

### CODE REVIEW

**Comment by awav** [comment]
@st--, Do you know why these changes reduce coverage?

**Comment by st--** [comment]
Yeah, I converted an 'assert' to a `raise TypeError`...

**Comment by jameshensman** [comment]
I agree with the new nomenclature, it's cleaner. 

But it might be good to add in a deprecationError, so that people whose code does `GPflow.kernels.(Add | Kern | Prod)` will get graceful failures.

**Comment by st--** [comment]
Any thoughts on `white` vs `whiten` vs `whitened` for argument to conditional() ?

**Comment by awav** [comment]
I like more `whitened`, then `white` ;)

**Comment by jameshensman** [comment]
@st-- could you have a look at this conflict, please? I'm struggling to see where test_ekerns.py neds to be changed

**Comment by st--** [comment]
Artem changed the tests to speed it up, so all that needed doing was accept the version from `master` and then go through and update nomenclature. Should all be working now, hopefully.

**Comment by st--** [comment]
NB- I had changed the arguments for the various conditionals `whiten` -> `white`; hadn't done that for SVGP (and subclasses such as in the test_uncertain_conditional) where it's still `whiten` as there that seemed to be appropriate name. Let me know if you want that changed as well, or if more people prefer `whitened` (James had preferred just `white`)...?

**Comment by st--** [comment]
If no-one's got any further comments, could you please merge this? It's a bit tiresome having to update my branch all the time to keep it mergeable & tests passing just because someone else has changed master again...

**Pull request merged**
