### PR TITLE
Autoflow fix bugfix

### LINKED ISSUE #54: Changing parameter to fixed requires model recompilation prior to prediction
Error is: ValueError: Cannot feed value of shape (4,) for Tensor u'Variable:0', which has shape '(5,)'
Error happens in predict_f  - full error trace below.

Minimal working example below.
Issue on master branch as of April 24, 2016.

### Code MWE - based on simple_regression.py
```
import GPflow
import tensorflow as tf
import os
import numpy as np
def getData():
    rng = np.random.RandomState( 1 )
    N = 30
    X = rng.rand(N,1)
    Y = np.sin(12*X) + 0.66*np.cos(25*X) + rng.randn(N,1)*0.1 + 3
    return X,Y
if __name__ == '__main__':
    X,Y = getData()
    k = GPflow.kernels.Matern52(1)
    meanf = GPflow.mean_functions.Linear(1,0)
    m = GPflow.gpr.GPR(X, Y, k, meanf)
    m.likelihood.variance = 0.01
    m._compile()
    print "Here are the parameters before optimization"
    print m
    m.kern.variance.fixed = True
    #m._compile() # If we compile again the code below works
    [mu,var] = m.predict_f(X)
    print mu
    print 'done'
```

### Trace:
```
Traceback (most recent call last):
  File "/Users/mqbssaby/PrivateProjects/BranchedGP/runfile.py", line 29, in <module>
    [mu,var] = m.predict_f(X)
  File "/Users/mqbssaby/pythonlibs/GPflow/GPflow/model.py", line 82, in runnable
    return instance._session.run(graph, feed_dict=feed_dict)
  File "/Users/mqbssaby/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Users/mqbssaby/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4,) for Tensor u'Variable:0', which has shape '(5,)'
```

### PR DESCRIPTION
**Pull request by jameshensman**
Fixes #54

### CODE REVIEW

**Comment by alexggmatthews** [comment]
Time limit exceeded I'm afraid.

**Comment by alexggmatthews** [comment]
My guess it is because we are doing more compiles. That tends to be the slow thing in the tests.

**Comment by jameshensman** [comment]
I really need to add an extra compile in here because the bug I'm fixing is
all about model compilation!

I'm talking to the codeship people to see if they can get us up and
running.

**Comment by alexggmatthews** [comment]
@jameshensman are you asking to merge this one?

**Comment by jameshensman** [comment]
Yeah this should be merged please.

**Pull request merged**
