### PR TITLE
VGP data update

### PR DESCRIPTION
**Pull request by javdrher**
Some minor fixes to perform the parameter updates of q_mu/q_sqrt for the VGP. This was broken after #612 , and when using the VGP as part of a Parameterized `compile()` was not called, so the code to update the parameters was moved to `_build()`

### CODE REVIEW

**Comment by markvdw** [comment]
Ah yes, it looks like I missed that out. You're also adding a `LowerTriangular` transform, which wasn't there earlier. Was that also a bug?

**Comment by javdrher** [comment]
On the cases I ran without the transform it worked, but it guess it should be there if it is part of original param? Ideally we'd take the current transform of `q_sqrt` before replacing it in case it was changed to something else by the user, but the transform might need to be updated for the new `num_latent` which differs for each transform.

**Comment by markvdw** [comment]
Ok, so this feature was added specifically for your use case?

Could we recreate the transform if the existing transform is `LowerTriangular`, since we know what to do then? Alternatively, we could raise an error or do a sensible default?

**Comment by javdrher** [comment]
This feature was added in 491b288a8636fb39ac1043b4a9648c5d6404f034 , long before GPflowOpt, our support for VGP relies on it

Right now it does recreate `LowerTriangular` regardless of the existing transform. Perhaps keep that, but issue a `UserWarning` if the transform was not a `LowerTriangular` ?
Alternatively, it seems only the LowerTriangular transform relies on `num_latent`, so we could just reuse the existing transform, and only intervene if its a `LowerTriangular`

**Comment by markvdw** [comment]
Hi @javdrher, sorry for being a bit out of touch with these PRs lately. We're doing a push to get back on track. Is this still relevant?

**Pull request merged**
