### PR TITLE
mlp kernel

### PR DESCRIPTION
**Pull request by jameshensman**
courtesy of @mrksr

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@mrksr Out of interest who are you?! I could find more than one Markus Kaiser online and I wasn't able to read the German on your webpage. Funny to have interacted so much without knowing this :)

**Comment by mrksr** [comment]
I am a PhD student in computer science at the TU Munich, but I am located at Siemens. I have just started my PhD in September and do not yet have a representative page to point you to - something that's on my to do list ;). Besides the TU Munich I do have some ties to Carl Henrik Ek who is in Bristol.

**Comment by mrksr** [comment]
Do you want me to write tests for the three missing lines or should they be ignored since they are only initialization-things?

**Comment by jameshensman** [comment]
tests would be great, please!

**Comment by mrksr** [comment]
You can pull from my `mlp-kernel`-branch: https://github.com/mrksr/GPflow/commit/bca5afd0c76d746c51d9da56504c16faf83bce00

**Comment by jameshensman** [comment]
This is really super @mrksr . It would be great to see a case study on this kernel using the SVIGP.

**Pull request merged**
