### PR TITLE
Corrected variables name in convolutional notebook for better underst…

### PR DESCRIPTION
**Pull request by prakharverma**
* [Title](#title) Convolutional GP notebook, variables corrected
* [Description](#description) There was a mismatch in the convolutional GP notebook variables which might result in confusion as the documentation is also created from it. The names of the variables are changed for better understanding.

### CODE REVIEW

**Comment by markvdw** [comment]
Looks great, thanks for the fixes!

**Comment by markvdw** [comment]
Are you happy for it to be merged now?

**Comment by prakharverma** [comment]
Yes, thank you!

**Comment by prakharverma** [comment]
Also, there is one more thing I wanted to confirm. In block 14, 15 (https://gpflow.readthedocs.io/en/master/notebooks/advanced/convolutional.html ) I don't see any changes. Is it purposedly done just to show that nothing changes?

**Comment by awav** [comment]
> Also, there is one more thing I wanted to confirm. In block 14, 15 (https://gpflow.readthedocs.io/en/master/notebooks/advanced/convolutional.html ) I don't see any changes. Is it purposedly done just to show that nothing changes?

That doc is generated from master. You will see your change in the doc once it is merged to the develop branch.

**Comment by prakharverma** [comment]
Yes, I understand. My question was not related to the changes I made but the existing code. I see those 2 blocks, block 14 and 15, as duplicate unless it's there to showcase that nothing changes. If not, then one of those blocks can also be deleted from the notebook.

**Pull request merged**
