### PR TITLE
add license text to all gpflow submodules

### PR DESCRIPTION
**Pull request by st--**
I noticed a bunch of repositories on github simply copied code from GPflow, perhaps mention "credit to GPflow" but otherwise don't make clear what code is from GPflow and how it got modified, if any. Technically this is in violation of our Apache license. This PR adds the license preamble to all source code files to make this clear.

Question: in the past people had put individual names on the copyright. What to do about that? For now I just copy&pasted a generic one that simply says "The GPflow Authors", which seems to be [common practice](https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/). Does that work for all of us?

### CODE REVIEW

**Comment by joelberkeley-pio** [comment]
> I noticed a bunch of repositories on github simply copied code from GPflow, perhaps mention "credit to GPflow" but otherwise don't make clear what code is from GPflow and how it got modified, if any. Technically this is in violation of our Apache license. This PR adds the license preamble to all source code files to make this clear.

I'd say we kindly ask them to follow the license rules where we spot an omission.

> Question: in the past people had put individual names on the copyright. What to do about that? For now I just copy&pasted a generic one that simply says "The GPflow Authors". Is that enough?

I'm pro "GPflow authors" partly cos it's less maintenance. In the cases where there were individual names, is it just a few names that are repeated across the code? If so, we could ask those people if they mind us changing it to "GPflow authors" and perhaps adding them to a list of past contributors somewhere

**Comment by st--** [comment]
> I'd say we kindly ask them to follow the license rules where we spot an omission.

I thought of that, but it mostly seemed to be write-once repos where someone put some code for a paper and hasn't touched it in the years after, so it didn't seem particularly worthwhile...

**Comment by markvdw** [comment]
I'm fine with "GPflow authors"

**Comment by st--** [comment]
I got in touch via e-mail with @PabloLeon @vals and @fujiisoup (who are not on the gpflow slack) who all confirmed they'd be happy with this proposal.

**Comment by st--** [comment]
We might want to change this to "Copyright The GPflow Contributors." or "Copyright Contributors to the GPflow project." to clarify that this includes everyone who's contributed to the code over the years, not just the original authors.

**Comment by st--** [comment]
@jameshensman @alexggmatthews all other contributors are happy with amending the copyright note as suggested - could you please get back to me with your thoughts ?

**Review by vdutor — APPROVED** [review]

**Pull request merged**
