### PR TITLE
Add jit flag to gpflow.optimizers.Scipy

### PR DESCRIPTION
**Pull request by st--**
As the Scipy optimizer combines numpy with tensorflow, we can't simply wrap its `minimize()` method in `tf.function()`. Instead, this PR adds a `jit` flag (True by default) which wraps the evaluation of objective and its gradients in `tf.function()`.

### CODE REVIEW

**Comment by awav** [comment]
@st-- , the thing is that we had `jit` in scipy and removed it.

**Comment by condnsdmatters** [comment]
> @st-- , the thing is that we had `jit` in scipy and removed it.

what was the motivation for getting rid of it? it looks faster for SVGP though not GPR

**Comment by awav** [comment]
@st-- , the reason for not having a jit flag is that `tf.function` doesn't work with many gpflow models. At the same time, there are cases when you need a special case gradient, or use might want to specialize either `tf.function` or `tf.function` without autograph.

**Comment by awav** [comment]
> > @st-- , the thing is that we had `jit` in scipy and removed it.
> 
> what was the motivation for getting rid of it? it looks faster for SVGP though not GPR

@condnsdmatters, check previous message

**Comment by condnsdmatters** [comment]
@awav which models do we know for a fact this _doesn't_ work with? sounds like we should fix if poss.

**Comment by awav** [comment]
@condnsdmatters every single one with multiple dispatch, it is not an easy fix. We can discuss it in person.

**Comment by st--** [comment]
All the tests pass, including the notebook tests, and I've not actually encountered any issues with the conditional(), so I don't think this is an immediate issue.

If you know of cases that would not work for this, please add it as a test case, so that we can work on fixing it!

**Pull request merged**
