### PR TITLE
Exclusive behaviour for Minibatch

### PR DESCRIPTION
**Pull request by awav**
Until https://github.com/tensorflow/tensorflow/issues/14633 is resolved, Minibatch should be kept from `auto-initializing` feature. Simple cases are not affected. Only when you switch between sessions you will have to re-initialize Minibatch explicitly.

### CODE REVIEW

**Comment by markvdw** [comment]
What is wrong with the behaviour that currently happens? Can you give an illustration?

**Comment by awav** [comment]
@markvdw, 
My assumptions for Minibatch:

```python
mini = gpflow.Minibatch(np.random.randn(500, 1))
mini.read_value(session=gpflow.get_default_session())
Out[6]: array([[-1.21374478]])

# emulate auto-initialize VVV
mini.initialize(force=True)
mini.read_value(session=gpflow.get_default_session())
Out[9]: array([[ 0.47700428]])
```

But SVGP has minibatch non-None seed, therefore whenever auto-initialize is called for *minibatches*, it will return the same sequence of minibatches:
```
N, D = 5000, 1
X = np.linspace(-2, 2, N).reshape(N, 1)
Y = np.zeros((N, 1))
svgp = SVGP(X, Y, RBF(D), Gaussian(), X.copy(), minibatch_size=2)
svgp.X.read_value(session=gpflow.get_default_session())
Out[15]:
array([[ 1.78635727],
       [ 1.25665133]])

svgp.X.initialize(force=True)
svgp.X.read_value(session=gpflow.get_default_session())
Out[17]:
array([[ 1.78635727],
       [ 1.25665133]])
```

It means that whenever you call autoflow method it will read same minibatch element from stream.

**Comment by markvdw** [comment]
Right, so to prevent the same minibatch from being returned by an autoflow method, we need to stop the minibatch from being re-initialised?

Just to check, is the autoflow case just an example, or can this behaviour show up anywhere other anywhere else?

I'll merge this soon.

**Comment by awav** [comment]
> Right, so to prevent the same minibatch from being returned by an autoflow method, we need to stop the minibatch from being re-initialised?
Exactly.

> Just to check, is the autoflow case just an example, or can this behaviour show up anywhere other anywhere else?
Optimization.

**Pull request merged**
