### PR TITLE
fixing tf version in setup.py

### PR DESCRIPTION
**Pull request by jameshensman**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Still fails here:

```bash
Switched to a new branch 'version_fix'
fonnescj on Marichal.local in ~/Repositories/GPflow(4m|version_fix)
$ pip install -U -e .                                  
Obtaining file:///Users/fonnescj/Repositories/GPflow
Requirement already up-to-date: numpy>=1.9 in /Users/fonnescj/anaconda3/lib/python3.5/site-packages (from GPflow==0.3.3)
Requirement already up-to-date: scipy>=0.16 in /Users/fonnescj/anaconda3/lib/python3.5/site-packages (from GPflow==0.3.3)
Collecting tensorflow>=0.11.0rc1 (from GPflow==0.3.3)
  Could not find a version that satisfies the requirement tensorflow>=0.11.0rc1 (from GPflow==0.3.3) (from versions: )
No matching distribution found for tensorflow>=0.11.0rc1 (from GPflow==0.3.3)
```

**Comment by jameshensman** [comment]
Oh. Could you post some more details of your setup, please? Anaconda python? tensorflow installed via pip? Thanks.

**Comment by fonnesbeck** [comment]
Running Anaconda Python 3.5.2. I used pip to install TF, following the website's instructions.

I am creating a conda virtualenv now to test whether there is something wrong in my current environment.

**Comment by fonnesbeck** [comment]
Yes, works fine in a virtualenv. My default environment must be hosed. Sorry for the trouble.

**Comment by jameshensman** [comment]
phew!

@alexggmatthews , could you look at merging this, please?

**Comment by alexggmatthews** [comment]
@fonnesbeck thanks for your interest in the software.
@jameshensman thanks for the PR.
Seems to work either way but this is probably more proper. Merging now.

**Pull request merged**
