### PR TITLE
GPflow python package name doesn't follow PEP8

### PR DESCRIPTION
**Pull request by awav**
Disscussion around this topic is in #452

### CODE REVIEW

**Comment by alexggmatthews** [comment]
I have also posted in #452

**Comment by tfwnicholson** [comment]
Grepping for "GPflow" shows up a lot of hits. Just to get it straight: we're rename the package but not the project?

**Comment by awav** [comment]
@tfwnicholson, Yes, only python package. The repository name should remain as is.

**Comment by alexggmatthews** [comment]
@awav did you intend to close the pull request?

**Comment by alexggmatthews** [comment]
@awav I still don't know why this one was closed. Can you explain, please?

**Comment by awav** [comment]
I apologize for confusion. I moved it to GPflow project branch, as some tests didn't work property for the fork. Unfortunately, there is no way to change PR source w/o closing old  and opening new PR.

**Comment by alexggmatthews** [comment]
OK no worries. Thanks for the reply.

**Pull request closed without merging**
