### PR TITLE
Fixed typo in \Lambda

### PR DESCRIPTION
**Pull request by joacorapela**
**PR type:** doc improvement

**Related issue(s)/PRs:** 
redos #1786

### CODE REVIEW

**Comment by jesnie** [comment]
I'm sorry, but this PR doesn't actually seem to include any changed files?

**Comment by joacorapela** [comment]
Hello @jesnie, I don't understand why the "Files Changed" tab does not show any changed files. However, if you look at the [Fixed typo in \Lambda](https://github.com/GPflow/GPflow/pull/1790/commits/3982e6a01bbb04aa90f4718031082adaddfa7d0e) commit in the the "Commits" tab you will see that I changed line 170 in [SGPR_notes.md](doc/source/notebooks/theory/SGPR_notes.md).

**Comment by st--** [comment]
@jesnie when you force-pushed, you accidentally overwrote the branch commit history. That's why it's empty. The relevant commit is https://github.com/GPflow/GPflow/commit/3982e6a01bbb04aa90f4718031082adaddfa7d0e - can you force-push it back to that?

**Comment by jesnie** [comment]
> @jesnie when you force-pushed, you accidentally overwrote the branch commit history. That's why it's empty. The relevant commit is [3982e6a](https://github.com/GPflow/GPflow/commit/3982e6a01bbb04aa90f4718031082adaddfa7d0e) - can you force-push it back to that?

I just hit the "Update branch" button in Github, and I'm afraid to touch anything like that again. But isn't the easiest thing to just do a new branch off of develop and redo the change? It's only a couple of characters.

**Comment by st--** [comment]
Ok, I finally figured out what's going on. What happened is that this typo _had_ already gotten fixed, by https://github.com/GPflow/GPflow/pull/1688 - so that's why everything disappeared once you merged develop back into the feature branch.

So the underlying issue was that for a while there had been an issue with the online docs generation. The [`develop` version](https://gpflow.readthedocs.io/en/develop/notebooks/theory/SGPR_notes.html) looks fine, but the [`master` version](https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html) hasn't gotten updated yet.

**Comment by st--** [comment]
So, in summary, the changes from this PR are actually in GPflow already! Just they haven't been propagated to the master version of readthedocs.

**Comment by joacorapela** [comment]
Thanks for the clarification @st--

**Comment by joacorapela** [comment]
I don't understand how my PR made it to the main branch, since none of the PR that I made have been merged.

**Pull request closed without merging**
