### PR TITLE
Upgrade for TensorFlow 2.10.

### PR DESCRIPTION
**Pull request by jesnie**
Start testing GPflow for TensorFlow 2.10.
Also slight update to format of `pip install`.

### CODE REVIEW

**Review by uri-granta — APPROVED** [review]
LGTM

**Comment by Corwinpro** [comment]
I think this now fails of m1 macos. I will investigate and update.

**Comment by jesnie** [comment]
> I think this now fails of m1 macos. I will investigate and update.
> 
> UPD: seems to be running fine on `python3.9` but fails on 3.10.

I assume it's because Google hasn't released the right packages yet, and that there isn't really anything we can do about it?

**Comment by Corwinpro** [comment]
I think so: using `python3.9` for default `gpflow` installation works just fine.

It might actually be a bug in the google's packages - there is `tensorflow-macos==2.10` for `python3.10` (and even 2.8, 2.9) but they don't work.

**Pull request merged**
