### PR TITLE
adding value property

### PR DESCRIPTION
**Pull request by st--**
Now tested.

Question: is there (or should there be) a test to compare setting of the same parameter in different sessions with different values?

### CODE REVIEW

**Comment by st--** [comment]
NB- I think the second assign (of self.m.p) should be a different number e.g. 3.0 and then there should be a check whether self.p is *also* 3.0 - if I'm understanding the concept correctly?

**Comment by alexggmatthews** [comment]
I'm happy to merge this unless someone has a good reason for value having been removed in 1.0 . I personally think read_value is a too verbose. @awav @jameshensman ?

**Comment by awav** [comment]
@alexggmatthews, @st-- I'm just curious if someone see my core review comments in PRs? :)

**Comment by alexggmatthews** [comment]
@awav I'm sorry I don't know what you mean.

**Pull request merged**
