### PR TITLE
Correction to link.

### PR DESCRIPTION
**Pull request by alexggmatthews**
Use tf 0.10 rather than the release candidate. Minor updates to readme.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@jameshensman  this one is ready to go.

**Comment by jameshensman** [comment]
Do we _require_ tf10? or will the rc do?

**Comment by alexggmatthews** [comment]
We don't require tf10 but I'm not sure if the release candidate version is officially supported. It isn't linked from the tf webpage for instance.

**Comment by alexggmatthews** [comment]
@jameshensman I just noticed intro.rst needed updating too. Going forward we probably don't want to have duplicate text in two files- I'll add an issue.

**Comment by alexggmatthews** [comment]
See #197 .

**Pull request merged**
