### PR TITLE
GPflow python package name doesn't follow PEP8

### PR DESCRIPTION
**Pull request by awav**
Copy of #451. Codeship and code coverage test didn't work for fork.
Disscussion around this topic is in #452.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@awav thank you for your PR. On the basis of the consensus of the community in the discussion in #452 I am happy to merge this when it is ready to go.

@awav We'll need to resolve the merge conflicts here obviously. Maybe re-run the automated script on new master?

The codeship failure is an interesting one. It relies on import GPflow but this command is unfortunately shared across all branches, including ones that use the old style. @jameshensman and I may need to treat this one in a special way to get it in. @jameshensman thoughts?

**Comment by awav** [comment]
@alexggmatthews, I've updated PR. `codeship` is failing in other branches too, since yesterday (August 9th). I do not have an access to take a look at the failure though. I see this at `codeship` "Oops! You can't access this page."

**Comment by awav** [comment]
@alexggmatthews, @jameshensman Could you give me an access to `codeship`, I would try to fix this thing, whatever it does :)

**Comment by alexggmatthews** [comment]
Because this requires some special treatment the GPflow team have decided it will be merged at a specific time:

**29th August at 1pm UK time.** All PRs afterwards will need to use the new name in the code. All PRs before will use the old naming convention. We don't anticipate that changing between the two naming conventions will be too difficult.

**Pull request merged**
