### PR TITLE
Rapela simplify calc psi in elbo and predict_f

### PR DESCRIPTION
**Pull request by joacorapela**
**PR type:** bugfix / enhancement / new feature / doc improvement

enhancement

**Related issue(s)/PRs:** 

follows up on #1685 and extends it to function predict_f.

**Note**
I think the formula for the predicted mean is incorrect. Please refer to #1753.

### CODE REVIEW

**Comment by jesnie** [comment]
It looks to me like this is exactly the same as #1754 ? Presumably we can close one of these PRs? Or maybe they need to be "untangled"?

**Comment by joacorapela** [comment]
@jesnie this PR implements the suggestion by @vdutor in #1685. Please ignore the changes in  [doc/source/notebooks/theory/SGPR_notes.md](doc/source/notebooks/theory/SGPR_notes.md) and look at those in [gpflow/models/gplvm.py](gpflow/models/gplvm.py). Sorry for the confusion.

**Review by jesnie — APPROVED** [review]
Approving, based on the approvals in #1754 and #1685 .

**Comment by st--** [comment]
Yes, it's the same branch in both PRs... @joacorapela for the future, it's better if you put independent sets of changes on different branches. @jesnie I've not reviewed the code changes, but the doc change in the notebook is fine.

**Pull request merged**
