### PR TITLE
Fixed typo in derivations of docs

### PR DESCRIPTION
**Pull request by joacorapela**
**PR type:** doc improvement

**Related issue(s)/PRs:** 
issue #1753

## Summary
Corrected a typo in the derivation of SGPR.

### CODE REVIEW

**Comment by jesnie** [comment]
I'll try and hit the `Update branch` button.

**Comment by jesnie** [comment]
Ok, that button doesn't seem to work well. I didn't mean to close your PR. Sorry.

**Comment by st--** [comment]
@jesnie looks like you accidentally nuked the commits :| @joacorapela could you try and reopen the pull request?

**Comment by st--** [comment]
Can you force-push it back to https://github.com/GPflow/GPflow/commit/3982e6a01bbb04aa90f4718031082adaddfa7d0e ?

**Pull request closed without merging**
