### PR TITLE
session configuration settings

### PR DESCRIPTION
**Pull request by alexisboukouvalas**
This hopefully address #209
As @kiudee pointed out in a cluster setting the tensorflow session may need to adhere to a limit on the number of cores used. 
I have attempted here to give a general solution where any config.proto setting can be passed to both model and autoflow sessions.
@markvdw @jameshensman are you happy with this solution?

Any ideas how to test autoflow session? It's not stored anywhere.

If you are happy with this, I am happy to add documentation for settings.session
Also note inter_op_parallelism_threads == '0 means the system picks an appropriate number.' [see here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto) so I think 0 is a reasonable default.

### CODE REVIEW

**Comment by markvdw** [comment]
This is great, exactly what I've been needing for a while as well.

The AutoFlow session can be accessed through a property with the name`storage_name = '_' + tf_method.__name__ + '_AF_storage'`, as defined in the `AutoFlow` decorator definition.

The only thing I would add, is to allow the user to override the config field in `kwargs`. I.e. the settings from `gpflowrc` should only be applied if no `config` option is passed to `get_session()`. My interpretation is that the priority should be defaults < settings file < overriding in the code.

**Comment by alexggmatthews** [comment]
I agree with Mark re settings file otherwise looks good.

**Comment by alexisboukouvalas** [comment]
I have added
1.  Caller of session.get_session can override config settings
1. Added tests for override behaviour and autoflow.
1. Added documentation in the settings notebook.

Thank you @alexggmatthews and @markvdw  for the review. 
If you are happy with the changes could you kindly merge them?

When testing the documentation changes I noticed the code was broken (missing import numpy as np).
Do you think it would be possible to run all the notebook in the documentation as part of the continuous integration tests? If so, I can open an issue.

**Comment by markvdw** [comment]
@alexisboukouvalas: Great, thanks for putting that in!

**Comment by alexisboukouvalas** [comment]
Should we close issue #209 ?

**Comment by jameshensman** [comment]
Please open an issue to run all notebook code in tests. Perhaps with ability to blacklist heavy notebooks.

**Pull request merged**
