### PR TITLE
Deterministic ordering of variable list to enable reproducible results with ScipyOptimizer

### LINKED ISSUE #416: Reproducibility using seeds
Been running some experiments, and it seems I cannot get the same reproducible result even when setting numpy and tensorflow seeds at the top of the script like

```
np.random.seed(72)
tf.set_random_seed(72)
```

Naturally, either I'm setting them wrong or I'm missing a RNG. I call Param.randomize() and Model.optimize(), and they seem to be the only sources of randomness at the moment (and I'm not even sure about the latter) so one of them is likely the culprit. Is there any way to either set the seed appropriately without messing with the source code or maybe adding an option allowing seeds to be set in the future?

### PR DESCRIPTION
**Pull request by jmxpearson**
- closes #416; similar in spirit to #417 
- Issue appears to affect only ScipyOptimizer. Does not affect, e.g.,
  AdamOptimizer on doc/source/notebook/classification
- Appears to be due to the fact that TensorFlow variables are not stably
  ordered across across replications, so var_list (and thus random
initial values for optimization) is not either.

### CODE REVIEW

**Comment by jameshensman** [comment]
@awav doesn't this code originate somewhere in tf.contrib?

**Comment by awav** [comment]
@jameshensman, nope. Fixed code from our repo.
@jmxpearson, I can see the issue: hashes for `set` elements changes depending on global python seed, so the order of var_list is different. The main question is how it affects ScipyOptimizer and why. Do you know answers? 
#416 is a bit different and not only about optimizers.

**Comment by jmxpearson** [comment]
There are two key pieces:

1. `ScipyOptimizer` is responsible for intializing the vector of parameters using numpy. The random piece of this is, of course, repeatable if one sets the numpy random seed.

1. However, the function that packs `Parameter`s into a single vector relies on the order in which the relevant `tf.Variable`s come out of `var_list`. So if this ordering isn’t stable, the various pieces of the vector `x` in the optimization are reordered from one run to the next and so initialized differently. 

In the case of the TensorFlow optimizers, the `Variable` packing is handled by tf, and if one sets the random seed in TensorFlow, this is done correctly and repeatably. 

My understanding was that #416 was just about getting repeatable results from setting random seeds. I only ran a subset of models, so it’s quite possible there are other factors influencing the repeatability from other models.

**Comment by awav** [comment]
Hello @jmxpearson. I apologize for not answering sooner. Can you show a case (mwe) when your change fixes the issue and w/o your fix breaks it. Thanks!

**Comment by jmxpearson** [comment]
As noted in the original PR, [this notebook](
https://github.com/GPflow/GPflow/blob/master/doc/source/notebooks/classification.ipynb)
produces inconsistent numerical results without the change and exactly the
same results with.

**Pull request merged**
