### PR TITLE
Quadrature

### PR DESCRIPTION
**Pull request by Bonnevie**
I have refactored the existing quadrature functions following the discussion for issue #306, and have made the necessary changes to all other files. The exception is ekernels.py, as the file's sole use of mvhermgauss seemed a bit complicated at first glance, so I thought it best to leave it for later. I have made sure that ekernels.py still works, though, but it should be fixed in the future. All existing tests finish without issue. 

EDIT: @markvdw might be interested.

EDIT2: I think I branched off at the wrong place, the multi-GP files (multilikelihoods.py and multimodels.py) are super-incomplete and shouldn't really be part of this pull request.

### CODE REVIEW

**Comment by markvdw** [comment]
Yes, you always want to branch off the latest master for a new PR. Shouldn't be too hard to fix, though you may want to start a new PR.

As for `ekernels.py`, I think we do want to fix this as well before accepting this PR. When there's a problem, it's best to fix it fully.

That said, I don't think it's going to be all too hard. Essentially, in `ekernels.Add. quad_eKzx1Kxz2`, a quadrature is performed over a multi input, multi output function. The input is `D` dimensional, and the grid is produced by `mvhermgaussI()` accordingly. The output of the function that we want to integrate against, is NxMxM. Essentially the `f` needs to return `cKa[:, :, None, :] * cKb[:, :, :, None]`, calculated for the quadrature `X`s.

**Comment by Bonnevie** [comment]
I have removed the files with an additional commit, but it might not be ideal. Is there any way to migrate the current changes to a branch off the master?

**Comment by markvdw** [comment]
Argh, I don't know git well enough for that stuff. Whenever this happens to me, I just copy the edited files somewhere separate, switch to master, and then paste them back :)

**Comment by mathDR** [comment]
Easiest way to do this would be to rebase against master:
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by alexggmatthews** [comment]
Hi everyone, I usually avoid rebases on the main repo unless absolutely necessary and I can't really see that it is in this case. I suggest a fresh PR if this one has gone wrong as per @markvdw suggestion.

**Comment by Bonnevie** [comment]
Think I got a clean branch going now, so I'll fix the ekernels.py file and then I'll make a new pull request.

**Comment by markvdw** [comment]
Great, thanks a lot! I'll close this one then for the time being.

**Pull request closed without merging**
