### PR TITLE
Print 1.0RC

### PR DESCRIPTION
**Pull request by jameshensman**
informally approved by @markvdw 

example:

```
In [7]: m = gpflow.models.GPR(X, Y, k)

In [8]: print(m)
<Parameter name:GPR/likelihood/variance [trainable] transform:+ve prior:None shape:()>
value: 1.0

<Parameter name:GPR/kern/variance [trainable] transform:+ve prior:None shape:()>
value: 1.0

<Parameter name:GPR/kern/lengthscales [trainable] transform:+ve prior:None shape:()>
value: 0.2
```

### CODE REVIEW

**Comment by markvdw** [comment]
This looks great. The previous version also supported html output, although this doesn't yet, right?

**Comment by jameshensman** [comment]
yeah, that's a separate feature I guess :)

**Comment by awav** [comment]
That's interesting and a bit buggy, and still it was merged ;)
@jameshensman, @markvdw look at:
https://github.com/GPflow/GPflow/commit/fac8000e2135575f622638107a06ff65ba381811#diff-d46540412624f87f1548383ea741d2abR387
https://github.com/GPflow/GPflow/commit/fac8000e2135575f622638107a06ff65ba381811#diff-d46540412624f87f1548383ea741d2abR118

**Comment by markvdw** [comment]
Wow that's embarrassing. I can submit a fix very soon. Good thing this isn't master ;)

**Comment by jameshensman** [comment]
ooh dear. Sorry. That first definition of __str__ should not be there!

**Pull request merged**
