### PR TITLE
Add NB and ZINB likelihoods

### PR DESCRIPTION
**Pull request by dirmeier**
**PR type:** new feature

## Summary

Ciao all, 

in case you're interested, this PR adds negative binomial and zero-inflated negative binomial likelihoods. The two are used fairly often, for instance in genomics, to model overdispersion in count data. If you want to merge this, I'd add some tests and use cases and clean it up a bit, otherwise feel free to close this again of course.

Cheers,
Simon

### Minimal working example

```python
n = 30
k = Exponential()

x = np.linspace(-1, 1, n).reshape(-1, 1)
f = tfd.MultivariateNormalTriL(
    np.repeat(0.0, x.shape[0]),
    tf.linalg.cholesky(k(x, x))
).sample(1, seed=23).numpy().reshape((n, 1))

y = tfd.NegativeBinomial(logits=f, total_count=10).sample(1, seed=23).numpy()
y = y.reshape((n, 1))

lik = ZeroInflatedNegativeBinomial()
m = gpflow.models.VGP((x, y),
                      mean_function=gpflow.mean_functions.Constant(),
                      likelihood=lik, kernel=k)

opt = gpflow.optimizers.Scipy()
opt.minimize(m.training_loss, variables=m.trainable_variables)
```

### CODE REVIEW

**Comment by st--** [comment]
Hi & welcome to the GPflow community! Thanks for your contribution. I had actually needed negative-binomial likelihood in a previous project. This is on the edge between "should just be its own package on top of GPflow" (maintained by you however you see fit, for as long as you care about) vs "should be in GPflow-core" (maintained by the GPflow maintainers, and in general for as long as the GPflow project keeps existing). I'd be willing to incorporate this into GPflow itself, but it'd be great if you could address the following points:
- [ ] Run `make format` to apply black's formatting to the code
- [ ] Add the appropriate setup to tests/gpflow/likelihoods/test_likelihoods.py to ensure the likelihood is tested
- [ ] Ideally add a notebook (or a section within a pre-existing notebook) that shows to users how to use the likelihood, maybe comparing against Poisson?

Would you be up for that ?

**Comment by st--** [comment]
One thought specific to negative binomial likelihood is that there's different parametrisations (type I, type II, and I believe some more that are less commonly used) - maybe good to make that explicit in the docstring? Or even provide both parametrisations.

**Comment by dirmeier** [comment]
> Would you be up for that ?

yeah, definitely, no problem.

**Comment by xliiauo** [comment]
Hi @dirmeier, thanks for your contribution, I was looking to implement the negative binomial likelihood as well before I found your PR here. More than happy to help with additional work to get this PR merged. Thank you.

**Comment by dirmeier** [comment]
Ciao @st-- ,
I've adapted the docstrings, added a notebook and updated the test setup for both negative binomial and its zero-inflated version. Since you didn't mention the ZINB, should I rather remove it here?

Cheers,
Simon

**Comment by dirmeier** [comment]
Ciao @st-- , did you find the time to have a look at this PR?

**Comment by mathDR** [comment]
bumping this.

**Pull request closed without merging**
