### PR TITLE
Fixed compile bug when using gcc5.

### LINKED ISSUE #173: error while importing GPflow
I can not import GPflow. I instelled it by  `python setup.py develop` on virtualenv. Tests are also failing to run.

### Import error
```
In [2]: import GPflow
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-d5391a053bbd> in <module>()
----> 1 import GPflow

/home/me/<...>/GPflow/GPflow/__init__.py in <module>()
     15 
     16 # flake8: noqa
---> 17 from . import likelihoods, kernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr
     18 from ._version import __version__

/home/me/<...>/GPflow/GPflow/likelihoods.py in <module>()
     17 import tensorflow as tf
     18 import numpy as np
---> 19 from .param import Parameterized, Param
     20 from . import transforms
     21 hermgauss = np.polynomial.hermite.hermgauss

/home/me/<...>/GPflow/GPflow/param.py in <module>()
     17 import pandas as pd
     18 import tensorflow as tf
---> 19 from . import transforms
     20 from contextlib import contextmanager
     21 from functools import wraps

/home/me/<...>/GPflow/GPflow/transforms.py in <module>()
     16 import numpy as np
     17 import tensorflow as tf
---> 18 import GPflow.tf_hacks as tfh
     19 
     20 

/home/me/<...>/GPflow/GPflow/tf_hacks.py in <module>()
     28 
     29 
---> 30 _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
     31 vec_to_tri = _custom_op_module.vec_to_tri
     32 tri_to_vec = _custom_op_module.tri_to_vec

/home/me/.virtualenvs/tf_0_10/lib/python2.7/site-packages/tensorflow/python/framework/load_library.pyc in load_op_library(library_filename)
     73           return _OP_LIBRARY_MAP[library_filename]
     74       # pylint: disable=protected-access
---> 75       raise errors._make_specific_exception(None, None, error_msg, error_code)
     76       # pylint: enable=protected-access
     77   finally:

NotFoundError: GPflow/tfops/matpackops.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

```

### Test error
```
running test
running egg_info
writing requirements to GPflow.egg-info/requires.txt
writing GPflow.egg-info/PKG-INFO
writing top-level names to GPflow.egg-info/top_level.txt
writing dependency_links to GPflow.egg-info/dependency_links.txt
reading manifest file 'GPflow.egg-info/SOURCES.txt'
writing manifest file 'GPflow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence']
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/me/.virtualenvs/tf_0_10/lib/python2.7/site-packages/setuptools/command/test.py", line 172, in run
    self.run_tests()
  File "/home/me/.virtualenvs/tf_0_10/lib/python2.7/site-packages/setuptools/command/test.py", line 193, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/me/.virtualenvs/tf_0_10/lib/python2.7/site-packages/setuptools/command/test.py", line 40, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_variational'

```

### PR DESCRIPTION
**Pull request by markvdw**
I felt compelled to fix #173. I couldn't test this on a machine with gcc5 though.

### CODE REVIEW

**Comment by jameshensman** [comment]
@BPie , could you confirm that this works for you, please?

**Comment by BPie** [comment]
Hi,
It doesn't work on my os.
my ` sys.platform` returns `linux2`, not `linux`.
Also 26 line:
` import re `
is redundant (line 4), imho.

**Comment by markvdw** [comment]
Whoops, I forgot that I actually already used `re` in there.

I changed the check to `sys.platform.startswith("linux")` as suggested by the Python docs. I tested it on Python 3, where it simply returns `linux`...

@BPie: Thanks for the test, could I ask you to test again?

**Comment by BPie** [comment]
@markvdw now it works well

**Comment by jameshensman** [comment]
Great stuff, merging.

**Pull request merged**
