### PR TITLE
Scoping

### PR DESCRIPTION
**Pull request by jameshensman**
Added some basic scoping functionality. 

1. I made a decorator in scoping.py. 
2. That decorator is applied in kullbackleiblers.py and conditionals.py
3. That decorator is automatically applied in any parameterized class where 'scoped_keys' has been defined.

### CODE REVIEW

**Comment by alexggmatthews** [comment]
@jameshensman why do we have two different code coverage tests at the moment? In this case we are currently waiting for one of them to be reported.

**Comment by jameshensman** [comment]
@alexggmatthews I guess codecov had a bit of an outage there. 

We have codecov and coveralls, but we don't depend on coveralls (it's not required to merge a commit). I'm happy to remove coveralls, which I don't rate, but I've left it there in case others are using it. 

This is the first time I've seen codecov have an outage, or be anything less that perfect.

**Comment by alexggmatthews** [comment]
@jameshensman Looks good. Let's get some test coverage to check that the names are working as expected.

@markvdw I'm pretty happy with this. As you were involved in discussing this on Thursday thought I would give you an opportunity to have a quick look. We're keen to use this to fix #181 so if I don't hear back from you 1pm today I will merge (subject to tests).

**Comment by markvdw** [comment]
I think this is a very elegant solution.

**Comment by alexggmatthews** [comment]
@jameshensman thank you for the PR - merging now.

**Pull request merged**
