### PR TITLE
Syntax changes for Python 3 compatibility

### PR DESCRIPTION
**Pull request by vals**
I think nowadays it fairly simple to keep Python 2/3 cross compatibility, so that would be nice. Here are some changes I needed to make before the package worked on Python 3.5.

### CODE REVIEW

**Comment by jameshensman** [comment]
Hi @vals 

Great! Any thoughts on running the tests in python 3 also, so that we don't break compatibility? I assume the tests pass for you?

**Comment by vals** [comment]
For continuous integration, there is a tool for running tests in multiple environments called tox: https://testrun.org/tox/latest/

I'm not sure what the normal behaviour is for developers working on cross-compatible packages. For me it was a rather large hassle to get everything working on one Python version in my compute environment. The thought of having to keep two version up to date sounds terrible...

I was just reading this page https://docs.python.org/3/howto/pyporting.html and found this cool tool: http://python-future.org/automatic_conversion.html , I'll try it out and see if it suggests other changes.

Regarding the tests, I did run them for quite a while, but had to catch a bus so had to stop them... How long are they supposed to run for? For me they were running for over 40 minutes. I figured the CI server would look at the pull request and tell if all things were working or not...

**Comment by vals** [comment]
I had some more patience with the tests, all work except these two:

    ==============================================================                                                                                                                                              ========
    ERROR: test_pred_density (testing.test_likelihoods.TestQuadrat                                                                                                                                              ure)
    --------------------------------------------------------------                                                                                                                                              --------
    Traceback (most recent call last):
      File "/nfs/research2/teichmann/valentine/GPflow/testing/test                                                                                                                                              _likelihoods.py", line 91, in test_pred_density
        liks = [l() for l in GPflow.likelihoods.Likelihood.__subcl                                                                                                                                              asses__()
      File "/nfs/research2/teichmann/valentine/GPflow/testing/test                                                                                                                                              _likelihoods.py", line 92, in <listcomp>
        if l.predict_density.__func__ is not GPflow.likelihoods.Li                                                                                                                                              kelihood.predict_density.__func__]
    AttributeError: 'function' object has no attribute '__func__'

    ==============================================================                                                                                                                                              ========
    ERROR: test_var_exp (testing.test_likelihoods.TestQuadrature)
    --------------------------------------------------------------                                                                                                                                              --------
    Traceback (most recent call last):
      File "/nfs/research2/teichmann/valentine/GPflow/testing/test                                                                                                                                              _likelihoods.py", line 74, in test_var_exp
        liks = [l() for l in GPflow.likelihoods.Likelihood.__subcl                                                                                                                                              asses__()
      File "/nfs/research2/teichmann/valentine/GPflow/testing/test                                                                                                                                              _likelihoods.py", line 75, in <listcomp>
        if l.variational_expectations.__func__ is not GPflow.likel                                                                                                                                              ihoods.Likelihood.variational_expectations.__func__]
    AttributeError: 'function' object has no attribute '__func__'

    --------------------------------------------------------------                                                                                                                                              --------
    Ran 104 tests in 6777.847s

I'm not sure what to do about those.

Also, note that the full test suite took almost 2 hours to run! Is that expected? Or is something wrong with my setup?

**Comment by jameshensman** [comment]
Wowsers, that is really long. It is very slow, but generally runs in 30
minutes or so on my macbook. Does it take that long for you in py2.7?

**Comment by vals** [comment]
I've been testing it with py2.7. Unlike before though, I'm now running the test suite on compute nodes. What I'm noticing now is that I get my jobs cancelled because the tests are using more memory than I've asked for.

It might have been that when I was running the test suites in interactive sessions, I ran out of RAM and would need to page to disk. That would explain it being slow. Do you see the test suite using a lot of RAM? Right now I'm trying with a 16 GB limit.

**Comment by jameshensman** [comment]
I've not noticed it using lots of ram, but I've never tried it on a machine
with limited memory. This could well explain why it fails (times out) on
the codeship/Travis servers.

**Comment by alexggmatthews** [comment]
@jameshensman I think that #67 may be relevant here.

**Comment by jameshensman** [comment]
I'm not sure why codeship hasn't posted the test results here. Possibly because the branchis nor in our repo? the tests pass though (see here: https://codeship.com/projects/147609/builds/15037063) so I'll merge.

**Comment by vals** [comment]
With 16 GB of RAM the tests passed for me too on Python 2.7. Just figured I should report that it took 1.5 hours...

    [...]
    ----------------------------------------------------------------------
    Ran 104 tests in 5821.051s
    
    OK

**Comment by alexggmatthews** [comment]
Hi @vals, Thanks for the feedback. That is a lot longer than it takes for me. What precise command are you using to run the tests, please? Alex

**Comment by vals** [comment]
Simply `python setup.py test`. I'm trying them now on my mac laptop. I'm not sure if it's GPflow or TensorFlow which is slow.

**Comment by alexggmatthews** [comment]
Thanks @vals I think it is worth getting to the bottom of this. I find that it can be slow to use setup.py . What happens if you run the shell script pasted I've pasted below from the base of the repo? 

time bash test.sh

begin contents of test.sh

python testing/test_autoflow.py
python testing/test_conditionals.py
python testing/test_hmc.py
python testing/test_kerns.py
python testing/test_likelihoods.py
python testing/test_mean_functions.py
python testing/test_method_equivalence.py
python testing/test_methods.py
python testing/test_model.py
python testing/test_param.py
python testing/test_predict.py
python testing/test_priors.py
python testing/test_transforms.py
python testing/test_variational.py

end test.sh

**Comment by jameshensman** [comment]
I prefer

pip install nose-timer
nosetests --nologcapture --with-timer testing

**Comment by alexggmatthews** [comment]
@jameshensman question is how long does that take on your desktop?

**Comment by jameshensman** [comment]
I don't recall exactly, but the longest test takes 5 minutes.

**Comment by alexggmatthews** [comment]
@jameshensman  Doing it my way the whole thing takes 

4m44.605s

**Comment by jameshensman** [comment]
Oh.  that's quite a difference!

**Comment by jameshensman** [comment]
In case anyone reading this is wondering, we made the tests run *much* faster by introducing `tf.reset_default_graph` at the start of each test. This clears the graph and makes subsequent computation a lot faster.

**Comment by vals** [comment]
Yes, much faster! (~5 minutes) Thanks!

(I'll stop writing in this thread now...)

**Pull request merged**
