### PR TITLE
Use only np_float[int] in code.

### PR DESCRIPTION
**Pull request by awav**
Because TensorFlow accepts numpy dtypes, there is no need in `tf_float` and `tf_int`. For now, I marked `tf_like` setting properties as deprecated.

### CODE REVIEW

**Comment by markvdw** [comment]
This looks good, but should we not just rename `np_type` to `dtype` or something? @jameshensman?

**Comment by awav** [comment]
@markvdw do you mean float[int]_dtype?

Other options:
* inttype, floattype
* int_type, float_type
* dtype_float, dtype_int
* type_float, type_int

:)

**Comment by st--** [comment]
I'd much prefer float_type and int_type. Whereas np_float seems ambiguous with np.float, which it is not, it's the specific precision type used throughout GPflow - whether tensorflow or numpy is used for any specific calculation, and I think calling the selected precision float_type better highlights that distinction. It's also consistent with settings.dtypes.float_type that has been around for ages (and for which settings.float_type is simply a shorthand).

**Comment by awav** [comment]
Agree, `float[int]_type` is better.

**Comment by markvdw** [comment]
Agreed. So we shouldn't see any more references to `np_float` in the code after this, right?

**Comment by alexggmatthews** [comment]
@awav thank you for your pull request. I've marked as don't merge until we make the agreed changes.

**Comment by alexggmatthews** [comment]
@awav I am happy to merge this once we have resolved CI. Is the codecov/patch failure I'm getting spurious?

**Pull request merged**
