### PR TITLE
Universal autoflow

### PR DESCRIPTION
**Pull request by jameshensman**
This PR moves the autoflow functionality from the model class to the param class

This was movitated by the desire to compute the kernel matrix without constructing a model.

At the same time, the autoflow mechansim has been simplified: maintainance will hopefully be easier.

### CODE REVIEW

**Comment by jameshensman** [comment]
This is an alternative to #63

**Comment by alexggmatthews** [comment]
@jameshensman Looks good to me. Thank you.

**Comment by ialong** [comment]
Hi guys, 
Sorry to bother you again, I've been trying to wrap my head around why the following code does not work:

```
kern = GPflow.ekernels.RBF(Ee, ARD=True)

eval_K = GPflow.param.AutoFlow((tf.float64,))(lambda kernel, input: kernel.K(input))
k = eval_K(kern, z)

eval_exKxz = GPflow.param.AutoFlow((tf.float64,),(tf.float64,),(tf.float64,))(lambda kernel, z, x, xx: kernel.exKxz(z, x, xx))
exkxz = eval_exKxz(kern, z, xmu, xcov)  
```

I'm constructing two AutoFlow instances with the appropriate number of arguments (the second calls a kernel expectation function) and yet the second value ```exkxz``` ends up being the same as the first (```k```). Do I need to start two independent tensorflow sessions?

@markvdw any thoughts?

Alessandro

**Comment by mrksr** [comment]
The problem you are running into is essentially the difference between the wrong and the "right" solution I described in #383. The two autoflowed functions behave the same because you have a collision in the way AutoFlow does caching and therefore `eval_exKxz` just reuses the graph of `eval_K`. The reason is that the caching is done based on the name of the autoflowed function, both of which are lambdas in your case which are called `__main__.<lambda>` (or something similar) and therefore collide.

This would not happen if
1) You use different kernels so the caching domains are different
2) You rename your functions so there is no collision

This should work:
```python
kern = GPflow.ekernels.RBF(Ee, ARD=True)

def _eval_K(kernel, input):
    return kernel.K(input)
eval_K = GPflow.param.AutoFlow((tf.float64,))(_eval_K)
k = eval_K(kern, z)

def _eval_exKxz(kernel, z, x, xx):
    return kernel.exKxz(z, x, xx)
eval_exKxz = GPflow.param.AutoFlow((tf.float64,),(tf.float64,),(tf.float64,))(_eval_exKxz)
exkxz = eval_exKxz(kern, z, xmu, xcov)  
```

**Comment by ialong** [comment]
@mrksr That's great, thank you very much!!

**Pull request merged**
